### ISSUE TITLE
Error when running, module not found: postcss-modules-extract-imports

### ISSUE THREAD

**Issue by yknl** [blockstack/animal-kingdom#10]
After I clone the repo and `npm install` I run into this module not found error when starting using `npm start`

Module not found: postcss-modules-extract-imports

Adding the `postcss-modules-extract-imports` package to package.json and reinstalling fixes it.

I'm using node v8.11.3

**Comment by moxiegirl** [comment]
@yknl I'm using 6.4.1.  I'll check with @larrysalibra and see which node his is using.

**Comment by raulgomezcorrales** [comment]
I had similar issues when I was trying to install from the .zip file. Everything worked fine after I cloned the app from Github instead.

**Comment by larrysalibra** [comment]
I'm not really sure what version of node I using. @yknl can someone at Blockstack PBC take a look at this?

**Comment by raulgomezcorrales** [comment]
Ubuntu 18.04.3 LTS
I have not been able to reproduce the error myself, after I cloned it, the .zip installation works ok as well.

What I can share is the output of npm install, there are some warnings there, but as I said, now it works fine

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.6 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1476 packages from 770 contributors and audited 889638 packages in 65.392s
found 16290 vulnerabilities (16289 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by raulgomezcorrales** [comment]
@moxiegirl @yknl thanks for your support! seems difficult to replicate error though, good to have this thread opened just in case someone else faces similar issue but I am all right now :-)

**Comment by moxiegirl** [comment]
Fine. I'm going to close this for now.
