### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by anugrahsinghal** [blockstack/animal-kingdom#100]
https://zealous-nightingale-8d6b51.netlify.com

anugrahsinghal.id.blockstack

**Comment by moxiegirl** [comment]
@anugrahsinghal Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
