### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by pcdavis** [blockstack/animal-kingdom#102]
https://stoic-hawking-dd2218.netlify.com

sancho_panza.id.blockstack

**Comment by moxiegirl** [comment]
@pcdavis Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
