### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by betosmith2000** [blockstack/animal-kingdom#103]
https://gallant-volhard-0ab9bf.netlify.com

betosmith2000.id.blockstack

**Comment by moxiegirl** [comment]
@betosmith2000 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
