### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by asopinka** [blockstack/animal-kingdom#104]
https://brave-agnesi-fc7d2b.netlify.com/

alexsopinka.id.blockstack

**Comment by moxiegirl** [comment]
@asopinka Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

🌮 🌮

**Comment by asopinka** [comment]
Thanks! 😄
