### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by dartman10** [blockstack/animal-kingdom#105]
https://zen-poincare-743126.netlify.com

dartman100.id.blockstack

**Comment by moxiegirl** [comment]
@dartman10 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
