### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by RajathAV** [blockstack/animal-kingdom#106]
https://hopeful-noether-0883fc.netlify.com/me

rajathav.id.blockstack

**Comment by moxiegirl** [comment]
@RajathAV Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
