### ISSUE TITLE
animal kingdom deployin CORS solution

### ISSUE THREAD

**Issue by AhmadRezaSaadatkhah** [blockstack/animal-kingdom#107]
In "deploying your Dapp on the web" part, after copying _headers and _redirects files to build directory in no.13 it's said that run the "npm run build" again. But it seems wrong because after running this code the folder became like before without the files and we will receive the same error. But if we dragging the build folder without running the code it has the files and the error will disappear.

**Comment by moxiegirl** [comment]
Good catch. Thank you. I'll fix that.

**Comment by moxiegirl** [comment]
Issue moved to [blockstack/docs.blockstack #180](https://github.com/blockstack/docs.blockstack/issues/180) via [**ZenHub**](https://www.zenhub.com/)
