### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by SeanJCasey** [blockstack/animal-kingdom#109]
https://upbeat-mccarthy-43697d.netlify.com

seancasey.id.blockstack

**Comment by moxiegirl** [comment]
@SeanJCasey Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Love the red!
