### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by wellsmt** [blockstack/animal-kingdom#110]
https://wizardly-wiles-125c49.netlify.com

emptywells.id.blockstack

**Comment by moxiegirl** [comment]
@wellsmt Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Moar SUN! 🌞
