### ISSUE TITLE
Please add my kingdome to your clan

### ISSUE THREAD

**Issue by takattty** [blockstack/animal-kingdom#111]
https://gracious-elion-08d8b6.netlify.com/

takatthokinawa.id.blockstack

**Comment by moxiegirl** [comment]
@takattty Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
