### ISSUE TITLE
Please add my kingdom to you clain!

### ISSUE THREAD

**Issue by camperal** [blockstack/animal-kingdom#112]
https://eloquent-kepler-13171c.netlify.com/

camperal.id.blockstack

**Comment by moxiegirl** [comment]
@camperal Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
