### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by pschhikara88** [blockstack/animal-kingdom#113]
https://pre-kingdom-336989.netlify.com

pschhikara88.id.blockstack

**Comment by moxiegirl** [comment]
@pschhikara88 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
