### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Manank95** [blockstack/animal-kingdom#114]
https://reverent-newton-f66a3f.netlify.com

manank9595.id.blockstack

**Comment by moxiegirl** [comment]
@Manank95 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
