### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by DavidFransch** [blockstack/animal-kingdom#115]
https://wizardly-roentgen-791914.netlify.com/me

safe_ware.id.blockstack

**Comment by moxiegirl** [comment]
@DavidFransch Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
