### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Hijiringo** [blockstack/animal-kingdom#116]
https://hopeful-kirch-f5a0ce.netlify.com/

jerryjerrygood.id.blockstack

**Comment by moxiegirl** [comment]
@Hijiringo Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
