### ISSUE TITLE
Plz add my 屋台 to your clan

### ISSUE THREAD

**Issue by wildmolasses** [blockstack/animal-kingdom#118]
https://cocky-spence-96f8bc.netlify.com/

wildmolasses.id.blockstack

**Comment by moxiegirl** [comment]
@wildmolasses Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
