### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by avcdsld** [blockstack/animal-kingdom#119]
https://wonderful-benz-f442d5.netlify.com

arandoros.id.blockstack

**Comment by moxiegirl** [comment]
@avcdsld Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
