### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by sagarchoudhary96** [blockstack/animal-kingdom#12]
https://optimistic-kepler-bb37b2.netlify.com/

sagarchoudhary96.id.blockstack

**Comment by moxiegirl** [comment]
@sagarchoudhary96 Thank you for the pull request and for completing the Zero-to-Dapp tutorial. You have been added to the clan.

**Comment by Hijiringo** [comment]
https://hopeful-kirch-f5a0ce.netlify.com/

jerryjerrygood.id.blockstack

**Comment by moxiegirl** [comment]
@Hijiringo This issue was closed.  I've opened this issue for you: https://github.com/blockstack/animal-kingdom/issues/117
