### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by kakke18** [blockstack/animal-kingdom#120]
https://boring-borg-980465.netlify.com

kakke18_perry.id.blockstack

**Comment by moxiegirl** [comment]
@kakke18 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
