### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ChanPoyu** [blockstack/animal-kingdom#121]
https://xenodochial-perlman-eda622.netlify.com/me

**Comment by moxiegirl** [comment]
@ChanPoyu what is your user ID? I can't add you to the clan without it.

**Comment by ChanPoyu** [comment]
@moxiegirl this is my id dipsyChan.id

**Comment by moxiegirl** [comment]
Thanks @ChanPoyu All sorted. Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
