### ISSUE TITLE
Please add my kingdom to you clan!

### ISSUE THREAD

**Issue by ryokomy** [blockstack/animal-kingdom#122]
https://hungry-wiles-ddb112.netlify.com

ryokomy3.id.blockstack

**Comment by moxiegirl** [comment]
Love the sky @ryokomy! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
