### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by sarakawa626** [blockstack/animal-kingdom#123]
https://mystifying-hugle-0685a9.netlify.com

sarakawa626.id.blockstack

**Comment by moxiegirl** [comment]
@sarakawa626 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
