### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by nobkovskii** [blockstack/animal-kingdom#124]
https://keen-fermi-c1e5f3.netlify.com

nobkovskii.id.blockstack

**Comment by moxiegirl** [comment]
@nobkovskii Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
