### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by AcidLeroy** [blockstack/animal-kingdom#125]
https://mystifying-tesla-0fc17a.netlify.com/

acidleroy.id.blockstack

**Comment by moxiegirl** [comment]
@AcidLeroy Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
