### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by shubham-s** [blockstack/animal-kingdom#126]
https://quirky-mcnulty-bc977b.netlify.com/

devil1331.id.blockstack

**Comment by moxiegirl** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
