### ISSUE TITLE
New kingdom comes a knocking..

### ISSUE THREAD

**Issue by thinkverse** [blockstack/animal-kingdom#127]
https://silly-joliot-e3dbed.netlify.com/

thinkverse.id.blockstack

**Comment by moxiegirl** [comment]
@thinkverse Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by thinkverse** [comment]
Already done that, though I never got an email about the t-shirt.. 😕

**Comment by moxiegirl** [comment]
@thinkverse you should get one today or tomorrow.  We send those when I process your application mining submission. I did that today so our shop manager will be sending out the tshirt email as soon as she can.  If you don't receive an email by Wednesday, let me know.
