### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by OctavianCoffman** [blockstack/animal-kingdom#128]
https://mystifying-montalcini-5975b6.netlify.com/

octavian.id.blockstack

**Comment by moxiegirl** [comment]
Nice choice there with the map! @OctavianCoffman Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
