### ISSUE TITLE
add my kingdom to clan

### ISSUE THREAD

**Issue by ashleys22** [blockstack/animal-kingdom#129]
https://unruffled-jennings-f51797.netlify.com

goashleysu.id.blockstack

**Comment by moxiegirl** [comment]
@ashleys22 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
