### ISSUE TITLE
Add me kingdom hoommies

### ISSUE THREAD

**Issue by ZachBordelon** [blockstack/animal-kingdom#130]
https://determined-mayer-5da20c.netlify.com

dames.id.blockstack

**Comment by moxiegirl** [comment]
Something about this kingdom tells me I could get good meal there. @ZachBordelon Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
