### ISSUE TITLE
Add me to the clan!

### ISSUE THREAD

**Issue by MurphyPone** [blockstack/animal-kingdom#131]
https://gallant-lewin-0565e3.netlify.com

petersmurphy7.id.blockstack

**Comment by moxiegirl** [comment]
@MurphyPone Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
