### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by kevinrmccraney** [blockstack/animal-kingdom#132]
https://nervous-bardeen-84fa52.netlify.com

maozedong.id.blockstack

**Comment by moxiegirl** [comment]
@kevinrmccraney Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
