### ISSUE TITLE
Hello, please add my kingdom to your clan!

### ISSUE THREAD

**Issue by lsamano** [blockstack/animal-kingdom#133]
https://heuristic-villani-a61306.netlify.com

leizlsamano.id.blockstack

Thank you!

**Comment by moxiegirl** [comment]
You are welcome --- and welcome to the clan! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
