### ISSUE TITLE
Add my kingdom!

### ISSUE THREAD

**Issue by omgitsgod** [blockstack/animal-kingdom#134]
url : https://jovial-boyd-7f5f10.netlify.com
id: omgitsgod.id.blockstack

**Comment by moxiegirl** [comment]
@omgitsgod  Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
