### ISSUE TITLE
Please add my kingdom!

### ISSUE THREAD

**Issue by evolfo** [blockstack/animal-kingdom#135]
https://naughty-williams-f3fae0.netlify.com

aspampinato.id.blockstack

**Comment by moxiegirl** [comment]
Good kingdom choice there! @evolfo Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
