### ISSUE TITLE
Please add my kingdom!

### ISSUE THREAD

**Issue by umairisrar** [blockstack/animal-kingdom#136]
https://awesome-allen-b964c2.netlify.com

umairisrar.id.blockstack

**Comment by moxiegirl** [comment]
@umairisrar Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
