### ISSUE TITLE
A new kingdom has risen

### ISSUE THREAD

**Issue by robertchen234** [blockstack/animal-kingdom#137]
https://animalskingdoms.netlify.com

robertchendev.id.blockstack

**Comment by moxiegirl** [comment]
@robertchen234 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
