### ISSUE TITLE
Let's be friends

### ISSUE THREAD

**Issue by jefreybulla** [blockstack/animal-kingdom#138]
https://naughty-euclid-5ef4db.netlify.com/

jefreybulla.id.blockstack

**Comment by moxiegirl** [comment]
@jefreybulla Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
