### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by smoorjani** [blockstack/animal-kingdom#140]
https://wonderful-noyce-e06ea4.netlify.com/kingdom/null

samrajmoorjani.id.blockstack

Thanks!

**Comment by moxiegirl** [comment]
Space, the final frontier.  (Sadly, not Star Wars.) @smoorjani Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
