### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by jayankamdar** [blockstack/animal-kingdom#141]
https://angry-murdock-a2700c.netlify.com

jayankamdar.id.blockstack

**Comment by moxiegirl** [comment]
Blockland, it started small but now rules all. @jayankamdar Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
