### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by johnm216** [blockstack/animal-kingdom#142]
https://pensive-swirles-b2da89.netlify.com

botagranate.id.blockstack

**Comment by moxiegirl** [comment]
@johnm216 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
