### ISSUE TITLE
Please add my kingdom

### ISSUE THREAD

**Issue by SaigeDruid** [blockstack/animal-kingdom#143]
https://eager-snyder-3ee638.netlify.com

saigedruid.id.blockstack

**Comment by moxiegirl** [comment]
🌴 @SaigeDruid Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
