### ISSUE TITLE
Please add my kingdome!!

### ISSUE THREAD

**Issue by bubbabeck** [blockstack/animal-kingdom#145]
https://stupefied-shannon-286386.netlify.com

meteorologisk.id.blockstack

**Comment by moxiegirl** [comment]
@bubbabeck Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
