### ISSUE TITLE
Please add my kingdom

### ISSUE THREAD

**Issue by ykrueng** [blockstack/animal-kingdom#147]
https://animal-kingdom.netlify.com/

yasirahk.id.blockstack

**Comment by moxiegirl** [comment]
Spacey! @ykrueng Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
