### ISSUE TITLE
Lo! A new kingdom rises...

### ISSUE THREAD

**Issue by snikipierowicz** [blockstack/animal-kingdom#148]
sn-animal-kingdom.netlify.com
snmediaworks.id.blockstack

**Comment by moxiegirl** [comment]
Dig it, moles rule! @snikipierowicz Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
