### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by gitanshu** [blockstack/animal-kingdom#150]
https://youthful-snyder-19f045.netlify.com

gitanshu.id.blockstack

**Comment by moxiegirl** [comment]
@gitanshu  Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
