### ISSUE TITLE
please add my kingdom to your clan!

### ISSUE THREAD

**Issue by asyrafahamed** [blockstack/animal-kingdom#152]
https://affectionate-kilby-515d7c.netlify.com

silveroy.id.blockstack

**Comment by moxiegirl** [comment]
@asyrafahamed Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
