### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by andrewttran** [blockstack/animal-kingdom#153]
https://thirsty-kepler-7d0fbe.netlify.com

andrewttran.id.blockstack

**Comment by moxiegirl** [comment]
@andrewttran Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
