### ISSUE TITLE
Please add my Kingdom to your clan!

### ISSUE THREAD

**Issue by sonicsmith** [blockstack/animal-kingdom#156]
https://priceless-noyce-5b2a91.netlify.com

nicsmith.id.blockstack

**Comment by moxiegirl** [comment]
@sonicsmith Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
