### ISSUE TITLE
Please add my Kingdom to your Clan

### ISSUE THREAD

**Issue by GreatSmiles** [blockstack/animal-kingdom#157]
https://festive-benz-709427.netlify.com

superkaa.id.blockstack

**Comment by moxiegirl** [comment]
@GreatSmiles Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
