### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ArtoriaRen** [blockstack/animal-kingdom#158]
https://eager-goodall-d3f5e2.netlify.com

davina2019.id.blockstack

**Comment by moxiegirl** [comment]
Cool world! @ArtoriaRen Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
