### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by human94** [blockstack/animal-kingdom#160]
https://stoic-raman-89864e.netlify.com

adrianda.id.blockstack

**Comment by moxiegirl** [comment]
@human94 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
