### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by kelceywilson** [blockstack/animal-kingdom#162]
https://eager-boyd-c9beb0.netlify.com

kelceywilson.id.blockstack

**Comment by moxiegirl** [comment]
> “Beware the Jabberwock, my son! 
>       The jaws that bite, the claws that catch! 
> Beware the Jubjub bird, and shun 
>       The frumious Bandersnatch!” 

@kelceywilson Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
