### ISSUE TITLE
Please add my kingdom!

### ISSUE THREAD

**Issue by JordanaSimon** [blockstack/animal-kingdom#164]
https://elated-tereshkova-5fecd7.netlify.com

jsimon98

**Comment by moxiegirl** [comment]
@JordanaSimon Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Enjoyed speaking with you.  Thank you for very much for your time.
