### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by amqzong** [blockstack/animal-kingdom#165]
https://elastic-pike-f6a886.netlify.com

amqzong1.id.blockstack

**Comment by moxiegirl** [comment]
@amqzong Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Enjoyed speaking with you. Thank you very much for your time.
