### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Sahana-Srinivasan** [blockstack/animal-kingdom#166]
https://cocky-montalcini-e9b713.netlify.com

srinivasan.id.blockstack

**Comment by moxiegirl** [comment]
San Fran in the Sun! @Sahana-Srinivasan Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
