### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ctxzz** [blockstack/animal-kingdom#167]
https://tender-darwin-76d1ac.netlify.com

ctxzzzzz.id.blockstack

**Comment by moxiegirl** [comment]
@ctxzz Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
