### ISSUE TITLE
Please add my kingdom

### ISSUE THREAD

**Issue by dav3harry** [blockstack/animal-kingdom#168]
https://determined-hoover-e3a87a.netlify.com/

daveharry.id.blockstack

**Comment by moxiegirl** [comment]
@dav3harry Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
