### ISSUE TITLE
New kingdom for everyone

### ISSUE THREAD

**Issue by jecassis** [blockstack/animal-kingdom#169]
https://inspiring-goldwasser-7a68cd.netlify.com/

transistor.id.blockstack

**Comment by moxiegirl** [comment]
@jecassis Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
