### ISSUE TITLE
CORS not configured on netlify

### ISSUE THREAD

**Issue by friedger** [blockstack/animal-kingdom#17]
When sign in without local blockstack browser, browser.blockstack.org fails to retrieve information.

**Comment by moxiegirl** [comment]
@friedger should be. There is a step in the tutorial where I force this error to teach people about CORS. In the next step, they "fix" the problem.  Did you encounter this before or after the fix?

**Comment by friedger** [comment]
I encountered it on animalkingdoms.netlify.com

**Comment by moxiegirl** [comment]
Yikes! Sorry...I need to mod the deploy build and stop my manual copies. Thanks for the issue. Should be fixed now.
