### ISSUE TITLE
Please add my fresh kingdom to your clan

### ISSUE THREAD

**Issue by jnermano** [blockstack/animal-kingdom#171]
https://gallant-feynman-7d2107.netlify.com/

jnermano.id.blockstack

**Comment by moxiegirl** [comment]
@jnermano Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
