### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by emilsergiev** [blockstack/animal-kingdom#172]
https://practical-fermat-f46a63.netlify.com

emilsergiev.id.blockstack

**Comment by moxiegirl** [comment]
@emilsergiev Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
