### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by mikewill95** [blockstack/animal-kingdom#175]
https://priceless-wilson-8e57b1.netlify.com

michaelw.id.blockstack

**Comment by moxiegirl** [comment]
@mikewill95 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by moxiegirl** [comment]
@mikewill95 The email you entered in App.co for your tshirt didn't resolve on send.

**Comment by mikewill95** [comment]
That’s weird. Could it be sent here/ how do I remedy this?

**Comment by moxiegirl** [comment]
@mikewill95 You can email me mary@blockstack.com and I'll see about getting you a tshirt
