### ISSUE TITLE
Add me to clan!

### ISSUE THREAD

**Issue by ajtruex** [blockstack/animal-kingdom#176]
[https://confident-curran-bc4f99.netlify.com/](https://confident-curran-bc4f99.netlify.com/)

andrewtruex.id.blockstack

**Comment by moxiegirl** [comment]
@ajtruex Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
