### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by Kitemaker** [blockstack/animal-kingdom#177]
https://musing-jennings-9a8c76.netlify.com/
voiceappstudio.id.blockstack

**Comment by moxiegirl** [comment]
@Kitemaker Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
