### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by hongily25** [blockstack/animal-kingdom#179]
https://compassionate-heyrovsky-c539c0.netlify.com

hongily25.id.blockstack

**Comment by moxiegirl** [comment]
@hongily25 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
