### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by joerlop** [blockstack/animal-kingdom#180]
https://sad-albattani-b59b7a.netlify.com

jonathanerlich.id.blockstack

**Comment by moxiegirl** [comment]
@joerlop Chilling at the beach. Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
