### ISSUE TITLE
Please add my kingdon on your clan!

### ISSUE THREAD

**Issue by loreb76** [blockstack/animal-kingdom#181]
https://suspicious-heisenberg-ef115b.netlify.com

lorenzob.id.blockstack

**Comment by moxiegirl** [comment]
@loreb76 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
