### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by WillzMu** [blockstack/animal-kingdom#191]
https://epic-murdock-ed407f.netlify.com

wilfred8.id.blockstack

**Comment by moxiegirl** [comment]
@WillzMu Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
