### ISSUE TITLE
Please add my Irish kingdom to your clan! 

### ISSUE THREAD

**Issue by eamongwalsh** [blockstack/animal-kingdom#192]
https://quizzical-hamilton-c15107.netlify.com/

eamongwalsh.id

**Comment by moxiegirl** [comment]
@eamongwalsh Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
