### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by T-Jedsada** [blockstack/animal-kingdom#193]
https://brave-torvalds-530c16.netlify.com/

jedsada_tiwongvorakul.id.blockstack

**Comment by moxiegirl** [comment]
@T-Jedsada Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by T-Jedsada** [comment]
Thank Sir

**Comment by T-Jedsada** [comment]
@moxiegirl Sorry sir, I submit  "Blockstack Sample Application" to https://app.co/ 

but I don't receive an email confirm

**Comment by moxiegirl** [comment]
@T-Jedsada That is a separate process. You should receive an email within the week regarding your sample submission and tshirt!
