### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by hatskier** [blockstack/animal-kingdom#198]
https://kind-hermann-d712d6.netlify.com

hatskier.id.blockstack

**Comment by moxiegirl** [comment]
@hatskier What a zoo! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
