### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by atoroc** [blockstack/animal-kingdom#199]
https://goofy-fermi-447c0b.netlify.com

discover.id.blockstack

**Comment by moxiegirl** [comment]
@atoroc Life will out! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
