### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by GreyingRaven** [blockstack/animal-kingdom#200]
https://modest-yalow-9aa5aa.netlify.com

greyingraven.id.blockstack

**Comment by moxiegirl** [comment]
@GreyingRaven Hello fellow raven...and the swamp looks lively! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
