### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by rorychristianmurray** [blockstack/animal-kingdom#202]
https://rorysanimalkingdoms.netlify.com

rorychristianmurray.id.blockstack

**Comment by moxiegirl** [comment]
@rorychristianmurray Patchouli? It can be powerful true! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
