### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by robertwilliamallen** [blockstack/animal-kingdom#203]
https://practical-joliot-6c77e0.netlify.com/

robertwilliamallen.id

**Comment by moxiegirl** [comment]
@robertwilliamallen  Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
