### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by iswistore** [blockstack/animal-kingdom#204]
https://nervous-nightingale-8054b6.netlify.com/

iswistore.id.blockstack

**Comment by moxiegirl** [comment]
@iswistore Venezuela!! So beautiful. Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
