### ISSUE TITLE
Please add my kingdom to your clam!

### ISSUE THREAD

**Issue by jogam5** [blockstack/animal-kingdom#205]
https://sharp-fermi-ec89a5.netlify.com

josegabriel.id.blockstack

**Comment by moxiegirl** [comment]
@jogam5 Mexico! Viva! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
