### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by rajputd** [blockstack/animal-kingdom#206]
https://xenodochial-goldberg-1bc549.netlify.com/animals

ctrlaltdileep.id.blockstack

**Comment by moxiegirl** [comment]
@rajputd Mountain, so high! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
