### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by jonnydevop** [blockstack/animal-kingdom#207]
https://competent-ramanujan-21dc0b.netlify.com

juancabello.id.blockstack

**Comment by moxiegirl** [comment]
@jonnydevop Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
