### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by sujeethav** [blockstack/animal-kingdom#208]
https://pensive-fermat-b94acf.netlify.com

sujeethav02.id.blockstack

**Comment by moxiegirl** [comment]
@sujeethav Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
