### ISSUE TITLE
Add My Kingdom to your Clan

### ISSUE THREAD

**Issue by sree-ksl** [blockstack/animal-kingdom#210]
https://agitated-meitner-876cf1.netlify.com

tinkerbell.id.blockstack

**Comment by moxiegirl** [comment]
@sree-ksl Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
