### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by slamtrade** [blockstack/animal-kingdom#211]
https://sad-wilson-2f844e.netlify.com/

slamtrade.id.blockstack

**Comment by moxiegirl** [comment]
@slamtrade Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by slamtrade** [comment]
Thank you. Submitted to app.co
