### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by georgiokg10** [blockstack/animal-kingdom#212]
https://trusting-mcnulty-014bea.netlify.com

georgiokg10.id.blockstack

**Comment by moxiegirl** [comment]
@georgiokg10 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
