### ISSUE TITLE
Please add my kingdom to the clan!

### ISSUE THREAD

**Issue by datagangstar** [blockstack/animal-kingdom#213]
https://condescending-curie-b23195.netlify.com

datagangstar.id.blockstack

**Comment by moxiegirl** [comment]
@datagangstar Looks like you brought your instance down...I'm getting *Not Found* on that site.  I can't add you to the clan but can submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by moxiegirl** [comment]
@datagangstar Your site looks like it is down, so I couldn't add it. Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
