### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by Christopher-I** [blockstack/animal-kingdom#214]
https://romantic-wright-331655.netlify.com
chrisigbojekwe.id.blockstack

**Comment by moxiegirl** [comment]
@Christopher-I Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
