### ISSUE TITLE
Please add my  kingdom to your clan!

### ISSUE THREAD

**Issue by rafael-r-vivas** [blockstack/animal-kingdom#221]
https://inspiring-minsky-09ac2d.netlify.com

xbiospace1.id.blockstack

**Comment by moxiegirl** [comment]
@rafael-r-vivas Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
