### ISSUE TITLE
Please add my kingdom :D

### ISSUE THREAD

**Issue by vicesalles** [blockstack/animal-kingdom#222]
https://dreamy-noether-0952b6.netlify.com/kingdom/0xxx99xxx0.id.blockstack

0xxx99xxx0.id.blockstack

**Comment by moxiegirl** [comment]
@vicesalles Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
