### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by char-no** [blockstack/animal-kingdom#225]
https://focused-engelbart-811df4.netlify.com

siracharr.id.blockstack

**Comment by moxiegirl** [comment]
@char-no Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
