### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by EricHeredia** [blockstack/animal-kingdom#226]
https://fervent-lovelace-879be0.netlify.com/me

edhp4n1k.id.blockstack

**Comment by moxiegirl** [comment]
@EricHeredia Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
