### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ceeghee** [blockstack/animal-kingdom#228]
https://peaceful-brahmagupta-de4632.netlify.com/

devstack.id.blockstack

**Comment by moxiegirl** [comment]
@ceeghee Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

(Tho I did notice your site still had a CORS issue. You can see [how to fix that here](https://docs.blockstack.org/develop/zero_to_dapp_3.html#deploy-your-dapp-on-the-web).)
