### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by scalish** [blockstack/animal-kingdom#229]
https://vibrant-mestorf-c07df8.netlify.com

scalish.id.blockstack

**Comment by moxiegirl** [comment]
@scalish Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
