### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by davidshq** [blockstack/animal-kingdom#230]
https://sad-golick-7cf29e.netlify.com/

davidshq.id.blockstack

**Comment by moxiegirl** [comment]
@davidshq Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by davidshq** [comment]
@moxiegirl Thanks! I did submit the app to app.co same day I posted here. Do I need to do anything else? I don't think I've heard anything back.

**Comment by moxiegirl** [comment]
@davidshq Nope.  You should get an email with instructions on how to get your tshirt.  They send them out every couple of days. If you don't have one by next week this time, ping me back here.
