### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by haidong** [blockstack/animal-kingdom#231]
https://sad-bhabha-656055.netlify.com/
otterthedog.id.blockstack

**Comment by moxiegirl** [comment]
@haidong Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
