### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by feherandras95** [blockstack/animal-kingdom#232]
https://elegant-ardinghelli-75ae9a.netlify.com

andrasfeher.id.blockstack

**Comment by moxiegirl** [comment]
@feherandras95  Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
