### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ddorman16** [blockstack/animal-kingdom#234]
https://silly-clarke-a3f96f.netlify.com/

ddorman.id

**Comment by moxiegirl** [comment]
@ddorman16 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

The throne sunk!
