### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by cnegrisanu** [blockstack/animal-kingdom#235]
https://laughing-heisenberg-a87a8f.netlify.com/

volucris.id.blockstack

**Comment by moxiegirl** [comment]
@cnegrisanu Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
