### ISSUE TITLE
Please please please add me to your clan!

### ISSUE THREAD

**Issue by shane-moore** [blockstack/animal-kingdom#236]
https://confident-colden-2a5eb4.netlify.com

shanekmoore.id.blockstack

**Comment by moxiegirl** [comment]
@shane-moore Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
