### ISSUE TITLE
Please add bakingpi kingdom to your clan!

### ISSUE THREAD

**Issue by SSMalvika** [blockstack/animal-kingdom#237]
https://gifted-elion-8ce162.netlify.com

bakingpi_blockstack.id.blockstack

**Comment by moxiegirl** [comment]
@SSMalvika Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Wow ‼️  What a wonderful fun job you did here. Thank you!
