### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by friedger** [blockstack/animal-kingdom#24]
https://planet.friedger.de

friedger.id

**Comment by moxiegirl** [comment]
@friedger Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
