### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by saimaclohessy** [blockstack/animal-kingdom#240]
https://zealous-mclean-75304f.netlify.com

trevorclohessy.id.blockstack

**Comment by moxiegirl** [comment]
@saimaclohessy Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
