### ISSUE TITLE
Please add my kingdom too!

### ISSUE THREAD

**Issue by eabedrapo** [blockstack/animal-kingdom#241]
https://compassionate-fermat-7b0a0b.netlify.com/

eabedrapo.id.blockstack

Thanks!

**Comment by moxiegirl** [comment]
@eabedrapo Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

BTW, looks like I am seeing this when I log into your kingdom:

![image](https://user-images.githubusercontent.com/1347209/60033667-dfa88900-965d-11e9-9bd3-056e086907f4.png)

You don't have to fix this, but if you want to the instructions are here:

https://docs.blockstack.org/develop/zero_to_dapp_3.html
