### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by samrobbins85** [blockstack/animal-kingdom#242]
https://inspiring-swartz-b34c0e.netlify.com

samrobbins.id.blockstack

**Comment by moxiegirl** [comment]
@samrobbins85 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
