### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by abdulmuqeeth** [blockstack/animal-kingdom#243]
https://hungry-brown-7cce75.netlify.com

abdulmuqeeth.id.blockstack

**Comment by moxiegirl** [comment]
@abdulmuqeeth Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
