### ISSUE TITLE
King Bodhi 

### ISSUE THREAD

**Issue by Bodhi-King** [blockstack/animal-kingdom#244]
https://dreamy-edison-0a9b55.netlify.com

kingbodhi.id.blockstack

**Comment by moxiegirl** [comment]
@Bodhi-King Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

🌳 🌳 🌳 🌳 🐦  🌳 🌳 🌳 🌳 🌳 Gaia rules!
