### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by chitech** [blockstack/animal-kingdom#245]
https://modest-dijkstra-a9343c.netlify.com

oneloves.id.blockstack

**Comment by moxiegirl** [comment]
@chitech Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

🏖 very nice addition! 🌞 + 🌊
