### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by praepunctis** [blockstack/animal-kingdom#246]
https://quirky-meitner-22ea5a.netlify.com

praepunctis.id.blockstack

**Comment by moxiegirl** [comment]
@praepunctis Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Heavens, what pretty clouds!
