### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by yunsite** [blockstack/animal-kingdom#247]
https://quirky-chandrasekhar-0a34ee.netlify.com
dappcoder.id.blockstack

**Comment by moxiegirl** [comment]
@yunsite Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
