### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by psgganesh** [blockstack/animal-kingdom#248]
https://docky-meninsky-b5f573.netlify.com

psgganesh.id.blockstack

**Comment by moxiegirl** [comment]
@psgganesh Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
