### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by smsunarto** [blockstack/animal-kingdom#249]
https://priceless-bhabha-3d5777.netlify.com

smsunarto.id.blockstack

**Comment by moxiegirl** [comment]
@smsunarto Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt. 

Castle of stone we salute you!
