### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by nenee** [blockstack/animal-kingdom#25]
https://dazzling-ptolemy-1e1411.netlify.com

fivebyfive.id.blockstack

**Comment by moxiegirl** [comment]
@nenee Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
