### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by gnewfield** [blockstack/animal-kingdom#250]
https://tender-yalow-e16b4d.netlify.com

gnewfield.id.blockstack

**Comment by moxiegirl** [comment]
@gnewfield Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Swim free my friend!
