### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by cmeese456** [blockstack/animal-kingdom#251]
https://upbeat-cray-a4b75b.netlify.com

kookajamo.id.blockstack

**Comment by moxiegirl** [comment]
@cmeese456 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Prepare for the next battle!
