### ISSUE TITLE
Please add my kingdom!

### ISSUE THREAD

**Issue by arav-agarwal2** [blockstack/animal-kingdom#252]
https://nostalgic-darwin-f50fab.netlify.com/

varalawraga.id.blockstack

**Comment by moxiegirl** [comment]
@arav-agarwal2 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
