### ISSUE TITLE
Hi, please add my kingdom to your clan!

### ISSUE THREAD

**Issue by aceparis32** [blockstack/animal-kingdom#253]
https://festive-goldstine-7168c0.netlify.com

aceparis32.id.blockstack

**Comment by moxiegirl** [comment]
@aceparis32 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Dust! Getting in the army's equipment.
