### ISSUE TITLE
completion of zero to dapp tutorial!

### ISSUE THREAD

**Issue by jihued16** [blockstack/animal-kingdom#256]
https://competent-clarke-7f7d25.netlify.com

aaron_avatm.id.blockstack

**Comment by moxiegirl** [comment]
@jihued16 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

John Denver would appreciate your kingdom!

**Comment by jihued16** [comment]
Im still developing my dApp. Hopefully in the next few weeks a version will be ready to roll out. I joined slack and the forum as well a few days ago incase i run into any issies but so far so good



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by moxiegirl** [comment]
@jihued16 That is entirely fine. The Zero to DApp is a way to get you going doing your own app.
