### ISSUE TITLE
Please add me to your clan !

### ISSUE THREAD

**Issue by ed1868** [blockstack/animal-kingdom#257]
http://127.0.0.1:3000/kingdom/blockhwek.id.blockstack

blockhwek.id.blockstack

**Comment by moxiegirl** [comment]
@ed1868 The URL you provided is a local one. That one can't join our clan, you need a deployed URL.  You can still submit that address. Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
