### ISSUE TITLE
Please add me and my kingdom to your clan!

### ISSUE THREAD

**Issue by davidjegan** [blockstack/animal-kingdom#258]
https://sleepy-chandrasekhar-f3beb4.netlify.com/

davidjegan.id.blockstack

**Comment by moxiegirl** [comment]
@davidjegan Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

An epic kingdom you built!

**Comment by davidjegan** [comment]
@moxiegirl Thanks. I highly appreciate it!
