### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by cdepman** [blockstack/animal-kingdom#26]
https://trusting-haibt-e87237.netlify.com

charlied.id.blockstack

**Comment by moxiegirl** [comment]
@cdepman Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
