### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by uyxela** [blockstack/animal-kingdom#261]
https://brave-wilson-8b6dc3.netlify.com

alexjhyu.id.blockstack

**Comment by moxiegirl** [comment]
@uyxela Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
