### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by JonathanXu1** [blockstack/animal-kingdom#262]
https://angry-jennings-ec278d.netlify.com

cardboard.id.blockstack

**Comment by moxiegirl** [comment]
@JonathanXu1 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
