### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by harrisbegca** [blockstack/animal-kingdom#263]
https://inspiring-spence-5714e5.netlify.com

shadowblock.id.blockstack

**Comment by moxiegirl** [comment]
@harrisbegca Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
