### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by deadcoder0904** [blockstack/animal-kingdom#264]
https://vigorous-minsky-b6a469.netlify.com

deadcoder0904.id.blockstack

**Comment by moxiegirl** [comment]
@deadcoder0904 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
