### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by wsmithparsec** [blockstack/animal-kingdom#265]
https://goofy-yalow-a092bc.netlify.com

warpsmith.id.blockstack

**Comment by moxiegirl** [comment]
@wsmithparsec Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
