### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by imdpkj** [blockstack/animal-kingdom#266]
https://pedantic-lumiere-b1877a.netlify.com

imdpkjangind.id.blockstack

**Comment by moxiegirl** [comment]
@imdpkj Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
