### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by adoankim** [blockstack/animal-kingdom#267]
https://thirsty-mcnulty-237372.netlify.com

adoankim.id.blockstack

**Comment by moxiegirl** [comment]
@adoankim Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Multiple dives!
