### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by E1Pistolero** [blockstack/animal-kingdom#268]
https://adoring-goodall-9cae4b.netlify.com

skylerknez.id.blockstack

**Comment by moxiegirl** [comment]
@E1Pistolero Your app has been removed so it is *Not Found* so we can't add you to our clan. However, you can still submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
