### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by shiowwj** [blockstack/animal-kingdom#272]
https://elegant-lalande-b83d6b.netlify.com

jamesshiow.id.blockstack

**Comment by moxiegirl** [comment]
@shiowwj Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
