### ISSUE TITLE
A clan and A kingdom

### ISSUE THREAD

**Issue by raresont** [blockstack/animal-kingdom#276]
https://nervous-beaver-d0848d.netlify.com

blocktestt.id.blockstack

**Comment by moxiegirl** [comment]
@raresont Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Romania -- fun place!
