### ISSUE TITLE
Please add my Kingdom to your clan!

### ISSUE THREAD

**Issue by Walterm21** [blockstack/animal-kingdom#281]
https://fervent-kalam-a029a8.netlify.com

mattwalter.id.blockstack

**Comment by moxiegirl** [comment]
@Walterm21 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Honk! Honk! Cars in the city.
