### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Atrop1** [blockstack/animal-kingdom#283]
https://boring-bohr-1651c7.netlify.com

petikovacs.id.blockstack

**Comment by moxiegirl** [comment]
@Atrop1 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Nice Westeros photo!
