### ISSUE TITLE
Please add my animal kingdom to your clan

### ISSUE THREAD

**Issue by bakkiraju** [blockstack/animal-kingdom#284]
https://musing-bassi-80f714.netlify.com

nimrujim.id.blockstack

**Comment by moxiegirl** [comment]
@bakkiraju Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
