### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by al002** [blockstack/animal-kingdom#285]
https://focused-payne-a74052.netlify.com/

al002042.id.blockstack

**Comment by moxiegirl** [comment]
@al002 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
