### ISSUE TITLE
I want to join the clan!

### ISSUE THREAD

**Issue by opheliagame** [blockstack/animal-kingdom#286]
https://mystifying-wiles-555dcb.netlify.com

opheliagame.id.blockstack

**Comment by moxiegirl** [comment]
@opheliagame You are in! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
