### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by 4btc4** [blockstack/animal-kingdom#288]
https://laughing-pare-7b4420.netlify.com

bictoiner.id.blockstack

**Comment by moxiegirl** [comment]
@4btc4 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
