### ISSUE TITLE
New Animal Kingdom!

### ISSUE THREAD

**Issue by craigusr** [blockstack/animal-kingdom#290]
https://hungry-liskov-cc96d8.netlify.com

craigusr.id.blockstack

**Comment by moxiegirl** [comment]
@craigusr Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Marley Joe! I approve.

**Comment by craigusr** [comment]
Hello, glad you like Marley Joe!

I already submitted the app per the instructions to app.co. Is there something else I need to do to receive the tee?

Thanks,
Craig

________________________________

**Comment by craigusr** [comment]
I see my id in the other kingdoms, but now when I log to my kingdom in I lost the picture of my dog.

I can go to other kingdoms and add Marley Joe from there, but the default dog shows up in Edit animal. All I can do is banish Marley.

Does this sound correct?

Curious on what exactly happened to add to the list of "other kingdoms"

Thanks,
Craig

________________________________

**Comment by moxiegirl** [comment]
@craigusr When I log into your Kingdom, I do see Marley:

![image](https://user-images.githubusercontent.com/1347209/61253480-0c5c3780-a716-11e9-932c-7d019b0ba04b.png)

I also added you to animalkingdoms...and see Marley there too.

![image](https://user-images.githubusercontent.com/1347209/61253719-cc498480-a716-11e9-9177-21deaf232884.png)


Hard to say why this was happening without knowing more. Did you edit the `constants.js` file and give a new file name for the picture or did you over write the `dog.jpg`?

I edit the `constants.js` file to add your kingdom to get it to appear. 

https://github.com/blockstack/animal-kingdom/blob/deploy/src/constants.js

**Comment by craigusr** [comment]
That's him all right! I think he showed up the first time and I might have screwed something up by doing a recursive add (adding Marley back to my kingdom).

I substituted marley's pic for the default Husky? like this:


export const ANIMALS = [

  {

    id: 'cat',

    name: 'Cat',

    superpower: 'Has 9 lives.'

  },

  {

    id: 'marley',

    name: 'Marley Joe',

    superpower: 'Chuck it!'

  },

  {

    id: 'lion',

    name: 'Lion',

    superpower: 'Roaring loudly.'

  }]


I should be able to update it by just re-uploading back to Netlify?

Curious, I could ask on the forum, but say I create an app which qualify's for an AppMining reward. What prevents anyone from looking at the javascript client code and copying it and resubmitting with slight mods and possibly taking away reward the next month? Should some code be "server side" without a server? I'm looking for an architecture diagram with boxes which shows where the physical (and logical) components live.

The white paper has a diagram for Gaia. Where can I find more diagrams like that :)

Thanks for you help,
Craig

________________________________

**Comment by moxiegirl** [comment]
> That's him all right! ..snip...I should be able to update it by just re-uploading back to Netlify?

Yes, that would be a good thing to do.


> Curious, I could ask on the forum, but say I create an app which qualify's for an AppMining reward. What prevents anyone from looking at the javascript client code and copying it and resubmitting with slight mods and possibly taking away reward the next month? Should some code be "server side" without a server? I'm looking for an architecture diagram with boxes which shows where the physical (and logical) components live. 

Honorable people don't do that, and everyone would call them out.  You could. But you should ask the forum anyway. 

> The white paper has a diagram for Gaia. Where can I find more diagrams like that :) Thanks for you help, Craig

Docs have a some diagrams.  

https://docs.blockstack.org/storage/overview.html
https://docs.blockstack.org/develop/overview_auth.html

I think you want more of an application architecture diagram --- got an example of one you think is particularly good.
