### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by raoden1** [blockstack/animal-kingdom#291]
https://blokckchainserviceapp.netlify.com

blockchainserviceapp.id.blockstack

**Comment by moxiegirl** [comment]
@raoden1 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Is Stormy a place or person?
