### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by grahamulator** [blockstack/animal-kingdom#292]
https://stoic-pike-20eba4.netlify.com

grahamulator.id.blockstack

**Comment by moxiegirl** [comment]
@grahamulator Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

@grahamulator Like your kingdom, I'm all in.
