### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by anuppani** [blockstack/animal-kingdom#293]
https://keen-feynman-e9f2e4.netlify.com
anuppani.id.blockstack

**Comment by moxiegirl** [comment]
@anuppani Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Interesting GOT pic.
