### ISSUE TITLE
Please add my kingdom to your clan! 

### ISSUE THREAD

**Issue by odubb** [blockstack/animal-kingdom#294]
https://xenodochial-gates-9c514b.netlify.com

omardubb.id.blockstack

**Comment by moxiegirl** [comment]
@odubb Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
