### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by mcarthurgill** [blockstack/animal-kingdom#295]
https://eager-kalam-54104d.netlify.com

mcarthur.id.blockstack

**Comment by moxiegirl** [comment]
@mcarthurgill Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
