### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by theprivileges** [blockstack/animal-kingdom#298]
https://focused-hopper-480e75.netlify.com/

luizlopes.id.blockstack

**Comment by moxiegirl** [comment]
@theprivileges Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Let the water move!
