### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by michaeljiflorida08** [blockstack/animal-kingdom#300]
https://relaxed-volhard-3b5598.netlify.com/

michaeljiflorida.id.blockstack

**Comment by moxiegirl** [comment]
@michaeljiflorida08 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Westeros!
