### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by KatherineWinter** [blockstack/animal-kingdom#301]
https://hungry-wozniak-1bcea8.netlify.com

gaslight.id.blockstack

**Comment by moxiegirl** [comment]
@KatherineWinter  Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
