### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by leogau** [blockstack/animal-kingdom#302]
https://lucid-mccarthy-b59d1b.netlify.com

leogau.id.blockstack

**Comment by moxiegirl** [comment]
@leogau Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Hobbit town!
