### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by TeunVanSambeek** [blockstack/animal-kingdom#304]
https://unruffled-swirles-8c800c.netlify.com
teunvansambeek.id.blockstack

**Comment by moxiegirl** [comment]
@TeunVanSambeek Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
