### ISSUE TITLE
Add my kingdom to your clan!

### ISSUE THREAD

**Issue by N470** [blockstack/animal-kingdom#305]
https://quizzical-raman-b26675.netlify.com
nullboots.id.blockstack

**Comment by moxiegirl** [comment]
@N470 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
