### ISSUE TITLE
Add my kingdom to your clan.

### ISSUE THREAD

**Issue by harsh-98** [blockstack/animal-kingdom#306]
https://nifty-murdock-36d05c.netlify.com

harshjain.id.blockstack

**Comment by moxiegirl** [comment]
@harsh-98 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

That is one intimidating Westeros!
