### ISSUE TITLE
Add my kingdom  to the clan plz

### ISSUE THREAD

**Issue by MarkGeeRomano** [blockstack/animal-kingdom#307]
https://vigilant-heyrovsky-f47611.netlify.com/

**Comment by moxiegirl** [comment]
@MarkGeeRomano what is your blockstack id, please?

**Comment by MarkGeeRomano** [comment]
whoops! markgeeromano.id.blockstack

thanks!

**Comment by moxiegirl** [comment]
@MarkGeeRomano Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Bold the lol at Westeros!
