### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by noahkirsch** [blockstack/animal-kingdom#309]
https://optimistic-chandrasekhar-45b84d.netlify.com

noahkirsch.id.blockstack

**Comment by moxiegirl** [comment]
@noahkirsch Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
