### ISSUE TITLE
Please Add My Kingdom to your Clan !!

### ISSUE THREAD

**Issue by ngerald51** [blockstack/animal-kingdom#31]
https://trusting-stonebraker-af1ebc.netlify.com/

ngerald51.id.blockstack

**Comment by moxiegirl** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
