### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ygbgames** [blockstack/animal-kingdom#310]
https://heuristic-clarke-7a7159.netlify.com

ygbdevid.id.blockstack

**Comment by moxiegirl** [comment]
@ygbgames Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Good choice on that Westeros image!
