### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ylawrence** [blockstack/animal-kingdom#311]
https://gracious-curran-893dfa.netlify.com

sodosopa.id.blockstack

**Comment by moxiegirl** [comment]
@ylawrence Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
