### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by SHagege** [blockstack/animal-kingdom#312]
https://suspicious-lichterman-145b39.netlify.com

cerealenthusiast.id.blockstack

**Comment by moxiegirl** [comment]
@SHagege Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
