### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by khajeet** [blockstack/animal-kingdom#314]
https://relaxed-williams-c74403.netlify.com

satomedia.id.blockstack

**Comment by moxiegirl** [comment]
@khajeet Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Deep in the sand!
