### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by spicynaresh** [blockstack/animal-kingdom#315]
https://upbeat-stonebraker-f2fd32.netlify.com

cryptohodler.id.blockstack

**Comment by moxiegirl** [comment]
@spicynaresh Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
