### ISSUE TITLE
Please add my kingdom into your clan!

### ISSUE THREAD

**Issue by taquitochowder** [blockstack/animal-kingdom#317]
https://quizzical-hugle-31365c.netlify.com

taquitochowder.id.blockstack

**Comment by moxiegirl** [comment]
@taquitochowder Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Altera alternative!
