### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by webwizart** [blockstack/animal-kingdom#318]
https://agitated-jackson-bd9cce.netlify.com/
w3bwizart.id.blockstack

**Comment by moxiegirl** [comment]
@webwizart Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Yokai? Wonderland!

**Comment by webwizart** [comment]
Thx, and already done
https://app.co/app/w3bwizart-kingdom
