### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by erikwlarsen** [blockstack/animal-kingdom#320]
https://app.netlify.com/sites/jolly-newton-fb6ca0/overview

erikwlarsen.id.blockstack

**Comment by moxiegirl** [comment]
@erikwlarsen Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Welcome to Hobbitown!
