### ISSUE TITLE
Please add me to your clan!

### ISSUE THREAD

**Issue by neoswarm** [blockstack/animal-kingdom#323]
https://pedantic-shannon-030ead.netlify.com/

neoswarm.id.blockstack

**Comment by moxiegirl** [comment]
@neoswarm Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
