### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by dhars0824** [blockstack/animal-kingdom#324]
https://vibrant-engelbart-f1b42e.netlify.com

dhars0824.id.blockstack

**Comment by moxiegirl** [comment]
@dhars0824 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Hope you can get some sleep.
