### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by aaronyih1** [blockstack/animal-kingdom#325]
https://inspiring-goldstine-c68a1d.netlify.com/

aaronyih.id.blockstack

**Comment by moxiegirl** [comment]
@aaronyih1 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

A little dark...but I guess so was Westeros.
