### ISSUE TITLE
Please add my kingdome!

### ISSUE THREAD

**Issue by adityaddy** [blockstack/animal-kingdom#327]
https://app.netlify.com/sites/stupefied-bartik-8d34c1/overview
adityakumar.id.blockstack

**Comment by shenshing** [comment]
Excuse me! do you get accept from Blockstack?

**Comment by moxiegirl** [comment]
@adityaddy Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Just West? I'm up for that. The Wolf you added rocks.
