### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by HardForksOverKnives** [blockstack/animal-kingdom#332]
https://inspiring-kowalevski-8dba54.netlify.com

connordunham.id.blockstack

**Comment by moxiegirl** [comment]
@HardForksOverKnives Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Into the mist goes the maiden!
