### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by wiredutch** [blockstack/animal-kingdom#334]
s://adoring-davinci-3e53eb.netlify.com/

vincentholland.onename.id

**Comment by moxiegirl** [comment]
@wiredutch Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
