### ISSUE TITLE
Please add my might kingdom to your clan!

### ISSUE THREAD

**Issue by SanchayPahalwani** [blockstack/animal-kingdom#335]
https://unruffled-cray-7d9e79.netlify.com

hellotest.id.blockstack

**Comment by moxiegirl** [comment]
@SanchayPahalwani Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

I control the elements!
