### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ashish343** [blockstack/animal-kingdom#336]
https://gallant-ramanujan-3ff903.netlify.com/

ashish_singhal.id.blockstack

**Comment by moxiegirl** [comment]
@ashish343 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
