### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by dgibney** [blockstack/animal-kingdom#337]
https://serene-shannon-84c47b.netlify.com

darrengibney.id.blockstock

**Comment by moxiegirl** [comment]
@dgibney Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
