### ISSUE TITLE
Please add my kingdom to clan

### ISSUE THREAD

**Issue by Pradam** [blockstack/animal-kingdom#339]
https://angry-hawking-803cf7.netlify.com/

pradamabhi.id.blockstack

**Comment by moxiegirl** [comment]
@Pradam Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
