### ISSUE TITLE
Please add my kingdom to you clan!

### ISSUE THREAD

**Issue by sjdev24** [blockstack/animal-kingdom#341]
https://frosty-jepsen-94536a.netlify.com

smitjivani.id.blockstack

**Comment by moxiegirl** [comment]
@sjdev24 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
