### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by pricky** [blockstack/animal-kingdom#343]
https://inspiring-ritchie-b8edfa.netlify.com/kingdom/
pricardo.id.blockstack

**Comment by moxiegirl** [comment]
@pricky Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Portugal is beautiful!
