### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by bamanczak** [blockstack/animal-kingdom#345]
https://brave-poincare-304966.netlify.com/

bmanczak.id.blockstack

**Comment by moxiegirl** [comment]
@bamanczak Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
