### ISSUE TITLE
Please add me to your clan!

### ISSUE THREAD

**Issue by aymentoumi** [blockstack/animal-kingdom#346]
https://nostalgic-dijkstra-f9758d.netlify.com

aymentoumi.id.blockstack

**Comment by moxiegirl** [comment]
@aymentoumi Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
