### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by brudnak** [blockstack/animal-kingdom#347]
https://elastic-wing-d76b60.netlify.com

andrewbrudnak.id.blockstack

**Comment by moxiegirl** [comment]
@brudnak Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
