### ISSUE TITLE
Please add me to your clan

### ISSUE THREAD

**Issue by ajithprasadanand** [blockstack/animal-kingdom#348]
https://ajithanand.netlify.com

ajithanand.id.blockstack

**Comment by moxiegirl** [comment]
@ajithprasadanand Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
