### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ShelbyDiamond** [blockstack/animal-kingdom#349]
https://fervent-boyd-29d884.netlify.com

shelbydiamond518.id.blockstack

**Comment by moxiegirl** [comment]
@ShelbyDiamond Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
