### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by zainraza** [blockstack/animal-kingdom#350]
https://focused-murdock-5b7c58.netlify.com

zainraza.id.blockstack

**Comment by moxiegirl** [comment]
@zainraza Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
