### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Mlira02** [blockstack/animal-kingdom#354]
https://affectionate-neumann-35fa68.netlify.com/

marcos19.id.blockstack

**Comment by moxiegirl** [comment]
@Mlira02 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
