### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by adityabp721** [blockstack/animal-kingdom#355]
https://musing-hamilton-01b31a.netlify.com

adityabp721.id.blockstack

**Comment by moxiegirl** [comment]
@adityabp721 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
