### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by NightlyD3V** [blockstack/animal-kingdom#356]
https://wonderful-beaver-325c6f.netlify.com
spaulding.id.blockstack

**Comment by moxiegirl** [comment]
@NightlyD3V Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
