### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by cargeins** [blockstack/animal-kingdom#357]
https://loving-wing-2bebe3.netlify.com
cargeins90.id.blockstack

**Comment by moxiegirl** [comment]
@cargeins Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
