### ISSUE TITLE
Hey! Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by progrmoiz** [blockstack/animal-kingdom#359]
https://brave-mahavira-d8b9c3.netlify.com/

samadmoiz.id.blockstack

**Comment by moxiegirl** [comment]
@progrmoiz Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
