### ISSUE TITLE
New kingdom to add to your clan!

### ISSUE THREAD

**Issue by larynab** [blockstack/animal-kingdom#360]
https://animal-kingdom-by-codelaryna.netlify.com

codelaryna.id.blockstack

**Comment by moxiegirl** [comment]
@larynab Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
