### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by chris-ian-jones** [blockstack/animal-kingdom#361]
https://fervent-minsky-cd3cf9.netlify.com/kingdom/chris_jones.id.blockstack

chris_jones.id.blockstack

**Comment by moxiegirl** [comment]
@chris-ian-jones Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
