### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by bruce366** [blockstack/animal-kingdom#362]
https://modest-engelbart-0eec5f.netlify.com/

brucechristie.id.blockstack

**Comment by moxiegirl** [comment]
@bruce366 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
