### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by jd1BAM** [blockstack/animal-kingdom#363]
https://sleepy-edison-00e58f.netlify.com

teamomucho.id.blockstack

**Comment by moxiegirl** [comment]
@jd1BAM Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
