### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by alonecuzzo** [blockstack/animal-kingdom#364]
https://infallible-brattain-c0f919.netlify.com

jabaribell.id.blockstack

**Comment by moxiegirl** [comment]
@alonecuzzo Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
