### ISSUE TITLE
Please add my kingdom to your clan !! 

### ISSUE THREAD

**Issue by Vermasaur** [blockstack/animal-kingdom#367]
https://hopeful-jang-c9ce1c.netlify.com

therealaverma.id.blockstack

**Comment by moxiegirl** [comment]
@Vermasaur Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
