### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by vedicastrology123** [blockstack/animal-kingdom#369]
https://vedicastrology.netlify.com

vedicastrology.id.blockstack

**Comment by moxiegirl** [comment]
@vedicastrology123 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by vedicastrology123** [comment]
Thanks
