### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by fractalswift** [blockstack/animal-kingdom#37]
https://reverent-pasteur-a4900c.netlify.com/

dubiousdog.id.blockstack

**Comment by moxiegirl** [comment]
@fractalswift Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
