### ISSUE TITLE
Please add my kingdom to your clan :)

### ISSUE THREAD

**Issue by greedychipmunk** [blockstack/animal-kingdom#371]
https://lucid-tereshkova-d5b7ef.netlify.com

dcblackhouse.id.blockstack

**Comment by moxiegirl** [comment]
@greedychipmunk Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
