### ISSUE TITLE
Add my kingdom to your clan!

### ISSUE THREAD

**Issue by ilogin** [blockstack/animal-kingdom#372]
pedantic-lamport-771322.netlify.com

raymonddeng.id.blockstack

**Comment by moxiegirl** [comment]
@ilogin Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
