### ISSUE TITLE
Please add my kingdom to your clan :D

### ISSUE THREAD

**Issue by ruwikmann** [blockstack/animal-kingdom#374]
https://boring-bhaskara-dfa4f0.netlify.com/

ruwikmann.id.blockstack

**Comment by moxiegirl** [comment]
@ruwikmann Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
