### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by xalsin** [blockstack/animal-kingdom#375]
I would be a worthy compatriot, fast with a repartee, faster with an evil laugh. 

https://wonderful-poincare-10850e.netlify.com

doctrina.id.blockstack

**Comment by moxiegirl** [comment]
@xalsin you are a truly terrifying Fire person, you empower the clan. Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
