### ISSUE TITLE
Please add my shadowhunter kingdom to your clan!

### ISSUE THREAD

**Issue by joberding** [blockstack/animal-kingdom#376]
https://shadowhunter-kingdom.netlify.com/
magnus_p8.id.blockstack

**Comment by moxiegirl** [comment]
@joberding We welcome the Demon Towers to our territory. Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
