### ISSUE TITLE
Please Add My Kingdom To Your Clan

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [blockstack/animal-kingdom#377]
https://admiring-ptolemy-ec6214.netlify.com

goodydev.id.blockstack

**Comment by moxiegirl** [comment]
@GoodnessEzeokafor Unique choices! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
