### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ryanckulp** [blockstack/animal-kingdom#378]
https://boring-booth-f1c5e6.netlify.com/

ryanckulp.id

**Comment by moxiegirl** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
