### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by csinozich** [blockstack/animal-kingdom#379]
https://nostalgic-noyce-bbfa1e.netlify.com/

clairesinozich.id.blockstack

**Comment by moxiegirl** [comment]
@csinozich Inventive photo! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
