### ISSUE TITLE
Please add me to your clan!

### ISSUE THREAD

**Issue by jorishermans** [blockstack/animal-kingdom#38]
https://focused-roentgen-9b4d74.netlify.com

jorishermans.id.blockstack

**Comment by moxiegirl** [comment]
@jorishermans Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by jorishermans** [comment]
I did but I think something went wrong when I register my app on app.co. I will try it again!

**Comment by jorishermans** [comment]
Done, I think it went better now :)
