### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by mukaissi** [blockstack/animal-kingdom#380]
mukaissi.id.blockstack

https://infallible-ardinghelli-d10b25.netlify.com

**Comment by moxiegirl** [comment]
@mukaissi Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
