### ISSUE TITLE
my beautiful kingdom

### ISSUE THREAD

**Issue by acays** [blockstack/animal-kingdom#383]
https://priceless-feynman-ab1a9f.netlify.com/kingdom/acayswen.id.blockstack

acayswen.id.blockstack

**Comment by moxiegirl** [comment]
@acays Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
