### ISSUE TITLE
Please add my kingdom

### ISSUE THREAD

**Issue by susanschen** [blockstack/animal-kingdom#384]
https://elegant-kingdom.netlify.com

lovegratitude.id.blockstack

**Comment by moxiegirl** [comment]
@Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Let the Magic Clan in!
