### ISSUE TITLE
UBUNTU: Error after selecting animal: TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by davisokoth** [blockstack/animal-kingdom#385]
After cloning and setting project up successfully, logging in and selecting an animal by clicking on its picture as described in [the tutorial](https://docs.blockstack.org/develop/zero_to_dapp_2.html), when I click `done` I get the following error on the next page that loads:
```
123 | <div className="row">
124 |   <div
125 |     className="col-lg-12 territory"
> 126 |     style={{backgroundImage: `url('${app}/territories/${rulerTerritory.id}.jpg')`}}
      | ^  127 |   >
128 |   { rulerAnimal && rulerAnimal.name ?
129 |     <img className="rounded-circle" src={`${app}/animals/${rulerAnimal.id}.jpg`} alt={rulerAnimal.name} />
```

Browser: Chrome 76.0.3809.100 (Official Build) (64-bit)
OS: Ubuntu 18

**Comment by moxiegirl** [comment]
@davisokoth We were not able to verify this in our environment test this week. We have seen results can vary depending on the Ubuntu environment setup.

**Comment by moxiegirl** [comment]
@davisokoth  Could you try starting the app with this `HTTPS=true npm start` instead of the standard `npm start` just as an experiment. Let me know if you still see that error.

**Comment by davisokoth** [comment]
@moxiegirl the error persists even when I use `HTTPS=true npm start`. Am not sure if the problem could be with the `animal` I am selecting since I realize that when `loadRuler(...)` on `Kingdom.js:67` returns the object has no `territory` property.

**Comment by davisokoth** [comment]
I have tried to change the animal and picked a few more but the error persists

**Comment by moxiegirl** [comment]
@davisokoth Other Ubuntu users have seen where cloning the code and then running it worked differently in Ubuntu.

What version of `npm` are you using? This is likely an environmental issue.  React doesn't always perform well under Ubuntu. You may find refining your environment for React helps.  Here is one set of instructions you may find helpful.

https://shift.infinite.red/painless-react-native-setup-for-mac-windows-linux-39e2e4d58d89
