### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ifgrcm** [blockstack/animal-kingdom#386]
https://affectionate-clarke-d65d70.netlify.com

iferreira.id.blockstack

**Comment by moxiegirl** [comment]
@ifgrcm Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
