### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Luis1D** [blockstack/animal-kingdom#388]
https://romantic-darwin-f8a291.netlify.com

luis_deanda.id.blockstack

**Comment by moxiegirl** [comment]
@Luis1D Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
