### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by wfehrnstrom** [blockstack/animal-kingdom#39]
fehrnstr.id.blockstack

https://cranky-spence-eef5f8.netlify.com

**Comment by moxiegirl** [comment]
@wfehrnstrom Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
