### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by JHaydenDev** [blockstack/animal-kingdom#390]
https://vigorous-hawking-4f97df.netlify.com/kingdom/jhaydendev.id.blockstack

jhaydendev.id.blockstack

**Comment by moxiegirl** [comment]
@JHaydenDev Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
