### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ok1a** [blockstack/animal-kingdom#391]
https://omar-okla-blockstack-animalkingdom.netlify.com/

omarokla.onename.id

**Comment by moxiegirl** [comment]
@ok1a Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
