### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by BM-Fisher** [blockstack/animal-kingdom#396]
https://amazing-varahamihira-7f2841.netlify.com

bmfisher.id.blockstack

**Comment by moxiegirl** [comment]
@BM-Fisher Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
