### ISSUE TITLE
Please add my Kingdom to your clan!

### ISSUE THREAD

**Issue by zchristy** [blockstack/animal-kingdom#397]
https://adoring-newton-494f04.netlify.com

zchristy.id.blockstack

**Comment by moxiegirl** [comment]
@zchristy Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
