### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ehalsmer** [blockstack/animal-kingdom#399]
https://happy-mccarthy-dbba17.netlify.com/kingdom/ehalsmer.id.blockstack

ehalsmer.id.blockstack

**Comment by moxiegirl** [comment]
@ehalsmer  Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
