### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ajohnson1031** [blockstack/animal-kingdom#400]
https://aj1031-blockstack-animal-kingdom.netlify.com

aj1031__.id.blockstack

**Comment by moxiegirl** [comment]
@ajohnson1031 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
