### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by cmfitzg2** [blockstack/animal-kingdom#401]
https://flamboyant-curran-8bb769.netlify.com
lordnarwhal.id.blockstack

**Comment by moxiegirl** [comment]
@cmfitzg2 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
