### ISSUE TITLE
Pease add my Kingdom to yur Clan.

### ISSUE THREAD

**Issue by egildio** [blockstack/animal-kingdom#402]
https://naughty-brahmagupta-bf0e6f.netlify.com/

dappfactory.id.blockstack

**Comment by moxiegirl** [comment]
@egildio Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Schure kan doo.
