### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by speratus** [blockstack/animal-kingdom#403]
https://gallant-wozniak-042e54.netlify.com/

sperator.id.blockstack

**Comment by moxiegirl** [comment]
@speratus Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
