### ISSUE TITLE
Please add my kindom to your clan!

### ISSUE THREAD

**Issue by 1Chr1s** [blockstack/animal-kingdom#404]
https://infallible-curie-5c3684.netlify.com

nerdychris.id.blockstack

**Comment by moxiegirl** [comment]
@1Chr1s Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
