### ISSUE TITLE
Please add my kingdom to your clan :)

### ISSUE THREAD

**Issue by johnmcguin** [blockstack/animal-kingdom#406]
https://angry-brown-2fbb9a.netlify.com

johnmcguin.id.blockstack

**Comment by moxiegirl** [comment]
@johnmcguin Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
