### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by stuebid** [blockstack/animal-kingdom#407]
https://amazing-lamarr-48e886.netlify.com

solution.id.blockstack

**Comment by moxiegirl** [comment]
@stuebid Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
