### ISSUE TITLE
Please add my kingdom to your clan. :D

### ISSUE THREAD

**Issue by Pyrospy** [blockstack/animal-kingdom#408]
https://modest-leakey-3b0731.netlify.com

pyrospyrody.id.blockstack

**Comment by moxiegirl** [comment]
@Pyrospy Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by Pyrospy** [comment]
Great :D Thank you. I already have submit my application to https://app.co/ on the 03. of September as written in the zero to dapp tutorial.
have a nice day!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Am Montag, September 9, 2019 5:30 AM schrieb Moxiegirl <notifications@github.com>:
