### ISSUE TITLE
Please add my kingdom to your clan 

### ISSUE THREAD

**Issue by adrianFMI** [blockstack/animal-kingdom#409]
https://eager-blackwell-82247d.netlify.com

adrianfm.id.blockstack

**Comment by moxiegirl** [comment]
@adrianFMI Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
