### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by jstrnbrg** [blockstack/animal-kingdom#41]
https://zealous-villani-bb5378.netlify.com

jstrnbrg.id.blockstack

**Comment by moxiegirl** [comment]
@jstrnbrg Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by jstrnbrg** [comment]
Hi Moxiegirl,

I thought I had already submitted my application to app.co ?
Did that not work ?

Kind regards,
Jo

Am Do., 27. Dez. 2018, 16:03 hat Moxiegirl <notifications@github.com>
geschrieben:

**Comment by moxiegirl** [comment]
@jstrnbrg This issue was regards to appearing in **Other Kingdoms** here: https://animalkingdoms.netlify.com/others.  To get added to App.co, you need to do Part iV. It sounds like you did do that. Our employee that manages that is on vacation. I can send you a confirmation email next week.
