### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by alexander7567** [blockstack/animal-kingdom#410]
https://upbeat-blackwell-6b07c7.netlify.com

darkstyrm.id.blockstack

**Comment by moxiegirl** [comment]
@alexander7567 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
