### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by devcshort** [blockstack/animal-kingdom#411]
https://youthful-goldwasser-4456b8.netlify.com

devcshort.id.blockstack

**Comment by moxiegirl** [comment]
@devcshort Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
