### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by csuito** [blockstack/animal-kingdom#412]
https://gallant-wescoff-d5e028.netlify.com

blockfreak.id.blockstack

**Comment by moxiegirl** [comment]
@csuito Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
