### ISSUE TITLE
Please add my kingdom to you clan!

### ISSUE THREAD

**Issue by pkdism** [blockstack/animal-kingdom#418]
https://modest-shaw-7b090b.netlify.com

flamingo.id.blockstack

**Comment by moxiegirl** [comment]
@pkdism Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
