### ISSUE TITLE
Please add my kingdom to you clan!

### ISSUE THREAD

**Issue by CMConsultant** [blockstack/animal-kingdom#419]
https://xenodochial-wescoff-209336.netlify.com/

yitsymc86.id.blockstack

**Comment by moxiegirl** [comment]
@CMConsultant Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
