### ISSUE TITLE
Please add me to your clan

### ISSUE THREAD

**Issue by trappierhall** [blockstack/animal-kingdom#42]
https://zealous-cray-e48eb6.netlify.com/kingdom/trappier.id.blockstack

trappier.id.blockstack

**Comment by moxiegirl** [comment]
@trappierhall Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
