### ISSUE TITLE
Please add my kingdom to your clan !!!

### ISSUE THREAD

**Issue by harshit777** [blockstack/animal-kingdom#421]
https://elegant-visvesvaraya-0ee302.netlify.com/

harshit7.id.blockstack

**Comment by moxiegirl** [comment]
@harshit777 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
