### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Nitro-T** [blockstack/animal-kingdom#422]
https://focused-curie-e04620.netlify.com

trautman.id.blockstack

**Comment by moxiegirl** [comment]
@Nitro-T Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
