### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by billax** [blockstack/animal-kingdom#423]
https://musing-shirley-883fc4.netlify.com

explorer.id.blockstack

**Comment by moxiegirl** [comment]
@billax Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
