### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by mjunaidasghar** [blockstack/animal-kingdom#424]
https://gracious-franklin-84624c.netlify.com

mjunaidasghar.id.blockstack

**Comment by moxiegirl** [comment]
@mjunaidasghar Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
