### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by jeff007ali** [blockstack/animal-kingdom#425]
https://ecstatic-haibt-d35f9e.netlify.com

jeff007ali.id.blockstack

**Comment by moxiegirl** [comment]
@jeff007ali Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
