### ISSUE TITLE
npm run build fails with minify errors on Windows 10

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/animal-kingdom#43]
I'm running into minify errors when attempting `npm run-build` on Windows 10.  

```
PS C:\animal-kingdom-master> npm run build

>	animal-kingdomgl.0.0-alpha.2 build C:\animal-kingdom-master
>	node scripts/build.js
Creating an optimized production build...

Failed to minify the code from this file:
./node_modules/bitcoinjs-lib/src/script.js: 57
Read more here: http://bit.ly/2tRViJ9
ELIFECYCLE 1
animal - kingdorrçQl. 0.0-alpha. 2 build: 'node scripts/build .js'
Exit status 1
Failed at the animal-kingdomgl.0.0-alpha.2 build script.
This is probably not a problem with npm. There is likely additional logging output above.
A complete log of this run can be found in:
C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-12-24T05_09_25_585Z-debug.log PS C:\animal-kingdom-master> —
```

Supposedly, the fix is to upgrade to react-scripts@>2.0.0 
https://facebook.github.io/create-react-app/docs/troubleshooting

Even after upgrading I'm still having this problem.

@larrysalibra Any ideas where to take it from here?  Is this an issue with our own react generator?

**Comment by moxiegirl** [comment]
Blocks: https://github.com/blockstack/docs.blockstack/issues/66

**Comment by zone117x** [comment]
@moxiegirl I can probably get this fixed. Can you assign to me? I don't have permissions to assign on this repo.

**Comment by moxiegirl** [comment]
Thanks @zone117x appreciate the hand.  Also, you should now have full on write perms.

**Comment by moxiegirl** [comment]
Fixed via https://github.com/blockstack/animal-kingdom/pull/56
