### ISSUE TITLE
please add my kingdom to your clan!

### ISSUE THREAD

**Issue by neterblock** [blockstack/animal-kingdom#430]
https://admiring-einstein-e2cbce.netlify.com

neterblock.id.blockstack

**Comment by moxiegirl** [comment]
@neterblock Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
