### ISSUE TITLE
New Kingdom in town!

### ISSUE THREAD

**Issue by jeremybrady702** [blockstack/animal-kingdom#433]
https://animal-kingdom.jeremybrady702.now.sh/

jeremybrady.id.blockstack

**Comment by moxiegirl** [comment]
@jeremybrady702 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Stays in Vegas...
