### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by jmlon** [blockstack/animal-kingdom#435]
https://zealous-wright-2138e0.netlify.com/

jorgelondono.id.blockstack

**Comment by moxiegirl** [comment]
@jmlon Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Dragons rock!
