### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by maniacdev** [blockstack/animal-kingdom#436]
https://elegant-mirzakhani-5975d3.netlify.com/

blockmonster.id.blockstack

**Comment by moxiegirl** [comment]
@maniacdev Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
