### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by clincl** [blockstack/animal-kingdom#437]
https://gallant-pasteur-ab6828.netlify.com

chuanlin.id.blockstack

**Comment by moxiegirl** [comment]
@clincl Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Very rocky!
