### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by drstm** [blockstack/animal-kingdom#438]
https://elated-mahavira-9ff8bc.netlify.com

dorsatum.id.blockstack

**Comment by moxiegirl** [comment]
@drstm Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Dorastum?
