### ISSUE TITLE
Guild Request

### ISSUE THREAD

**Issue by 5thdimension** [blockstack/animal-kingdom#44]
Please add me to your clan

https://animalkingdom5th.netlify.com

5thdimension.id.blockstack

**Comment by moxiegirl** [comment]
@5thdimension Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by 5thdimension** [comment]
@moxigirl  hello   just to.mwntion i dont see my kingdom on the list   is it normal ??

**Comment by moxiegirl** [comment]
@5thdimension It wasn't a @GinaAbrams  thing. I had forgotten to deploy your sample application to https://animalkingdoms.netlify.com/others  I did the code change and blithely went off holidaying...you should see it now.  Sorry for the confusion.

**Comment by 5thdimension** [comment]
ok yes GinaAbrams  trough email for appmining  and thanks ill chk url

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 5thdimension** [comment]
@moxiegirl  your app is missing the CORS setting 
https://animalkingdoms.netlify.com/others

cant be reach from all browser

**Comment by moxiegirl** [comment]
@5thdimension Thanks I have fixed that.
