### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by sparag90** [blockstack/animal-kingdom#441]
https://keen-dubinsky-2a34f4.netlify.com

sparag90.id.blockstack

**Comment by moxiegirl** [comment]
@sparag90 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
