### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by lillialskye** [blockstack/animal-kingdom#442]
https://frosty-mccarthy-76c1fd.netlify.com/kingdom

lillithrose.id.blockstack

**Comment by moxiegirl** [comment]
@lillialskye Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Lovely kingdom!
