### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by nimbustwothousand** [blockstack/animal-kingdom#444]
https://zealous-curie-1c5d61.netlify.com

nimbustwothousand.id.blockstack

**Comment by moxiegirl** [comment]
@nimbustwothousand Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

A castle but not a throne.
