### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by qrodgers13** [blockstack/animal-kingdom#445]
https://xenodochial-goldstine-04ec71.netlify.com/me

qrodgers.id.blockstack

**Comment by moxiegirl** [comment]
@qrodgers13 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
