### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by a-deal** [blockstack/animal-kingdom#447]
https://relaxed-jackson-680632.netlify.com/

andrewdeal.id.blockchain

**Comment by moxiegirl** [comment]
@a-deal Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by moxiegirl** [comment]
Beautiful Earth!
