### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ohfr** [blockstack/animal-kingdom#448]
https://nifty-engelbart-64b745.netlify.com/

danielmartin.id.blockstack

**Comment by moxiegirl** [comment]
@ohfr Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
