### ISSUE TITLE
Please Add My Kingdom To Your Clan!

### ISSUE THREAD

**Issue by cmahlobo** [blockstack/animal-kingdom#449]
https://adoring-yalow-a5c14f.netlify.com/kingdom/cmahlobo.id.blockstack

cmahlobo.id.blockstack

**Comment by moxiegirl** [comment]
@cmahlobo Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
