### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by tesla809** [blockstack/animal-kingdom#45]
https://distracted-saha-09847b.netlify.com

anthony_albertorio.id.blockstack

Love your docs! Cool project.

**Comment by moxiegirl** [comment]
@tesla809 Thank you for letting us know you enjoyed the docs!  And thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
