### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by aminukano585** [blockstack/animal-kingdom#450]
https://trusting-yalow-75bf93.netlify.com

aminukano.id.blockstack

**Comment by moxiegirl** [comment]
@aminukano585 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Not quite the throne -- tho maybe Bran did use that after the other was destroyed.
