### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by RickMJohn** [blockstack/animal-kingdom#451]
https://xenodochial-khorana-a3631a.netlify.com

rickjohn.id.blockstack

**Comment by moxiegirl** [comment]
@RickMJohn Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
