### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by Rexben001** [blockstack/animal-kingdom#452]
https://trusting-jepsen-2d4e16.netlify.com

rexben001.id.blockstack

**Comment by moxiegirl** [comment]
@Rexben001  Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
