### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by GoesUp** [blockstack/animal-kingdom#453]
https://elated-haibt-ebcdb9.netlify.com

onlygregor.id.blockstack

**Comment by moxiegirl** [comment]
@GoesUp Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Population!
