### ISSUE TITLE
Please add my kingdom!

### ISSUE THREAD

**Issue by CJLucido** [blockstack/animal-kingdom#456]
https://nimalssanssans.netlify.com

**Comment by CJLucido** [comment]
cjlucido.id.blockstack

**Comment by moxiegirl** [comment]
@CJLucido Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Nice Westeros!
