### ISSUE TITLE
cat clan

### ISSUE THREAD

**Issue by invegat** [blockstack/animal-kingdom#457]
https://gifted-hermann-02ef62.netlify.com

flvegath.id.blockstack

**Comment by moxiegirl** [comment]
@invegat Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
