### ISSUE TITLE
Please add my kingdom to the clan! 

### ISSUE THREAD

**Issue by SuragSheth** [blockstack/animal-kingdom#459]
https://stoic-lovelace-9328c2.netlify.com/

suragusheth.id.blockstack

**Comment by moxiegirl** [comment]
@SuragSheth Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
