### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by BettyXi** [blockstack/animal-kingdom#46]
https://modest-wescoff-dc0756.netlify.com

pantherapardus.id.blockstack

**Comment by moxiegirl** [comment]
@BettyXi Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
