### ISSUE TITLE
Please add my kingdom to you clan!

### ISSUE THREAD

**Issue by kristenfleming** [blockstack/animal-kingdom#461]
https://priceless-lichterman-b8ccca.netlify.com/

kristens.id.blockstack

**Comment by moxiegirl** [comment]
@kristenfleming Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
