### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Sam-Ford** [blockstack/animal-kingdom#464]
https://quirky-chandrasekhar-cfb8e0.netlify.com/

sjdftech.id.blockstack

**Comment by moxiegirl** [comment]
@Sam-Ford Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
