### ISSUE TITLE
Please add my wealthy kingdom to your clan!

### ISSUE THREAD

**Issue by entheo** [blockstack/animal-kingdom#466]
https://elegant-stonebraker-70fbf6.netlify.com
entheome.id.blockstack

**Comment by moxiegirl** [comment]
@entheo Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
