### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by imchriskitchens** [blockstack/animal-kingdom#468]
https://happy-hermann-c2356d.netlify.com

imchriskitchens.id.blockstack

**Comment by moxiegirl** [comment]
@imchriskitchens Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by imchriskitchens** [comment]
> @imchriskitchens Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others. Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Should sample apps be re-submitted to App.co .. if they do not include the username in the title? Quite a few have copied/pasted from the tutorial and missed this detail in the process.

**Comment by moxiegirl** [comment]
@imchriskitchens Good question.  The tutorial is not a test it is something you can try out. So, "mistakes" are optional and experimentation encouraged.  The idea is to drive the experience of submitting an application.

There are only two parts of the submission that are necessary -- that someone uses the *Sample Application` category and that you supply an email. These two things ensure users end up happy like this user:

https://twitter.com/pyrospyrody/status/1183813915400167426?s=19
