### ISSUE TITLE
Solve the vulnerabilities in the Animal Kingdom demo dapp

### ISSUE THREAD

**Issue by webwizart** [blockstack/animal-kingdom#474]
The app has a lot of npm vulnerabilities which should be solved  
<img width="618" alt="Screenshot 2019-10-15 at 01 31 16" src="https://user-images.githubusercontent.com/527613/66789383-91a8e100-eeeb-11e9-938c-b85555f9b5e4.png">

**Comment by friedger** [comment]
Interesting, using `yarn` all looks good.

![Screenshot from 2019-10-15 10-49-44](https://user-images.githubusercontent.com/1449049/66815963-89779280-ef39-11e9-96ef-603e6e6afeef.png)

**Comment by moxiegirl** [comment]
@friedger you are free to use yarn.  Not sure how the package managers handle the audits. We have standardized on NPM/npx tooling.  

In general, the output of this command is environment-dependent.  My output was closer to @webwizart but still different.

```
Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

added 1613 packages from 787 contributors and audited 889652 packages in 30.044s
found 16291 vulnerabilities (16290 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by moxiegirl** [comment]
@webwizart Post update I am seeing this:

```
Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

added 1611 packages from 786 contributors and audited 902622 packages in 21.711s
found 0 vulnerabilities
```

Thanks again for the issue, much appreciated!
