### ISSUE TITLE
Please add my Kingdom to your clam

### ISSUE THREAD

**Issue by criptolot** [blockstack/animal-kingdom#477]
https://amazing-kalam-60aa7c.netlify.com

rjtn1970.id.blockstack

**Comment by moxiegirl** [comment]
@criptolot Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by moxiegirl** [comment]
![image](https://user-images.githubusercontent.com/1347209/67170590-cabbd800-f367-11e9-838c-9e3311be4663.png)

Very cool!
