### ISSUE TITLE
Hi, please add my kingdom to your clan

### ISSUE THREAD

**Issue by MusabShakeel576** [blockstack/animal-kingdom#478]
https://objective-hugle-729f02.netlify.com

musabshakeel.id.blockstack

**Comment by moxiegirl** [comment]
@MusabShakeel576 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by moxiegirl** [comment]
Beautiful ocean!
