### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Aptifox** [blockstack/animal-kingdom#479]
https://sharp-archimedes-6db7ca.netlify.com

aptifox.id.blockstack

**Comment by moxiegirl** [comment]
@Aptifox Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by Aptifox** [comment]
Thanks!
