### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by gopye** [blockstack/animal-kingdom#48]
https://romantic-perlman-5483a9.netlify.com

gopye.id.blockstack

**Comment by moxiegirl** [comment]
@gopye Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
