### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Paintermark0** [blockstack/animal-kingdom#482]
https://infallible-yonath-01854f.netlify.com

paintermark0.id.blockstack

**Comment by moxiegirl** [comment]
@Paintermark0 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
