### ISSUE TITLE
Please add my kingdom to your Clan!

### ISSUE THREAD

**Issue by arjunangepat** [blockstack/animal-kingdom#484]
https://brave-goldberg-f93558.netlify.com/

arjunangepat.id.blockstack

**Comment by moxiegirl** [comment]
@arjunangepat Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
