### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by kwag** [blockstack/animal-kingdom#485]
https://elastic-neumann-2aafa0.netlify.com

kwagnert.id.blockstack

**Comment by moxiegirl** [comment]
@kwag Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
