### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by mjhoes** [blockstack/animal-kingdom#486]
https://happy-easley-511087.netlify.com

michaeljhoes.id.blockstack

**Comment by moxiegirl** [comment]
@mjhoes Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
