### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Asoka11111** [blockstack/animal-kingdom#487]
https://angry-ramanujan-8b933f.netlify.com/

sabroski_niggamoto.id.blockstack

**Comment by moxiegirl** [comment]
@Asoka11111 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
