### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by evgenyboxer** [blockstack/animal-kingdom#488]
https://eloquent-heyrovsky-bd9466.netlify.com

evgenyboxer.id.blockstack

**Comment by moxiegirl** [comment]
@evgenyboxer Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
