### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by jonnyphresh** [blockstack/animal-kingdom#49]
https://app.netlify.com/sites/sharp-bhabha-8fdd4c/deploys

jonnyphresh.id.blockstack

**Comment by moxiegirl** [comment]
@jonnyphresh Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by jonnyphresh** [comment]
Hey there,

just wondering if I’m ever going to receive a shirt?

Thanks,

Jon

**Comment by moxiegirl** [comment]
@jonnyphresh If you submitted your application to app.co you should have a received an email to get your tshirt. Did you get the email?

**Comment by jonnyphresh** [comment]
No, I have not.

**Comment by moxiegirl** [comment]
@jonnyphresh I didn't see your email address in your GitHub. If you want to drop it here I can send you the coupon to get a free tshirt!

**Comment by moxiegirl** [comment]
Sent.  Look for the heading **Your Zero-to-DApp Tshirt!** in your email.

**Comment by jonnyphresh** [comment]
Jonathansdjennings@gmail.com

Thank you so much!
