### ISSUE TITLE
Please add my Kingdom to our Clan!

### ISSUE THREAD

**Issue by patipravat** [blockstack/animal-kingdom#491]
https://romantic-brattain-a4c4ea.netlify.com

patipravat.id.blockstack

**Comment by moxiegirl** [comment]
@patipravat Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Wow, that's a lot of different animals! I love the mix. Very foxy wolf!

**Comment by moxiegirl** [comment]
#500
