### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by KhoaVanNguyen** [blockstack/animal-kingdom#492]
https://focused-swartz-1bb452.netlify.com/

khoanguyen.id.blockstack

**Comment by moxiegirl** [comment]
@KhoaVanNguyen Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Nice Westeros map!
