### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by whyaza** [blockstack/animal-kingdom#493]
https://dreamy-williams-f816e9.netlify.com

wuhongyu.id.blockstack

**Comment by moxiegirl** [comment]
@whyaza Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Liked your bird!
