### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Swap76** [blockstack/animal-kingdom#494]
https://clever-mccarthy-684c68.netlify.com/

swapnil76.id.blockstack

**Comment by moxiegirl** [comment]
@Swap76 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Good job!
