### ISSUE TITLE
Please add my kindom to your clan

### ISSUE THREAD

**Issue by fuzzyprogrammer** [blockstack/animal-kingdom#496]
https://ecstatic-mclean-51747c.netlify.com/

sikandar.id.blockstack

**Comment by moxiegirl** [comment]
@fuzzyprogrammer Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
