### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by SiddhantPanda** [blockstack/animal-kingdom#497]
https://determined-darwin-f5fd6e.netlify.com/

sidpanda99.id.blockstack

**Comment by moxiegirl** [comment]
@SiddhantPanda  Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
