### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by fhilip09** [blockstack/animal-kingdom#498]
https://gifted-kirch-dea874.netlify.com

fenrir09.id.blockstack

**Comment by moxiegirl** [comment]
@fhilip09 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Cool mountain kingdom!
