### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by wowbagger63** [blockstack/animal-kingdom#50]
https://upbeat-williams-577db4.netlify.com/kingdom/

wowbagger59.id.blockstack

**Comment by wowbagger63** [comment]
wowbagger63.id.blockstack

**Comment by moxiegirl** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
