### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by smartidiot** [blockstack/animal-kingdom#501]
https://pedantic-nightingale-bc34d4.netlify.com/

shishirsingh.id.blockstack

**Comment by moxiegirl** [comment]
@smartidiot Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
