### ISSUE TITLE
New Blockstack Kingdom!

### ISSUE THREAD

**Issue by thejoshcooter** [blockstack/animal-kingdom#502]
https://objective-kepler-996ef4.netlify.com/kingdom/joshcooter.id.blockstack

thejoshcooter.id.blockstack

**Comment by moxiegirl** [comment]
@thejoshcooter Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
