### ISSUE TITLE
Please add my Animal to your clan!

### ISSUE THREAD

**Issue by matthewbcool** [blockstack/animal-kingdom#505]
https://wonderful-shirley-e3e9d0.netlify.com

m_b_cool.id.blockstack

**Comment by moxiegirl** [comment]
@matthewbcool Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.


The desert is very extreme!
