### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Shadowborn** [blockstack/animal-kingdom#506]
https://shadowborn-kingdom.netlify.com/

shadowborn.id.blockstack

**Comment by moxiegirl** [comment]
@Shadowborn Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.


Out from the shadows into the clan!
