### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by jamesmartin** [blockstack/animal-kingdom#507]
https://amazing-bohr-2424b6.netlify.com/

jamesmartin.id.blockstack

**Comment by moxiegirl** [comment]
@jamesmartin Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
