### ISSUE TITLE
I wanna join your clan!

### ISSUE THREAD

**Issue by ShashankR87** [blockstack/animal-kingdom#509]
https://modest-thompson-1115f9.netlify.com/

shashankr.id.blockstack

**Comment by moxiegirl** [comment]
@ShashankR87 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
