### ISSUE TITLE
Add my kingdom to your clan!

### ISSUE THREAD

**Issue by bshreyas01** [blockstack/animal-kingdom#510]
https://cocky-colden-84424a.netlify.com/

thisisbatman.id.blockstack

**Comment by moxiegirl** [comment]
@bshreyas01 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
