### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by EmilianoG-byte** [blockstack/animal-kingdom#511]
https://goofy-bell-2be334.netlify.com/

emilianog.id.blockstack

**Comment by moxiegirl** [comment]
@EmilianoG-byte Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
