### ISSUE TITLE
Please add my kingdom

### ISSUE THREAD

**Issue by Sadanand150** [blockstack/animal-kingdom#512]
stupefied-sammet-b2fb08.netlify.com
bmwcrypto.id.blockstack

**Comment by moxiegirl** [comment]
@Sadanand150 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
