### ISSUE TITLE
Add kingdom to your clan

### ISSUE THREAD

**Issue by karansag** [blockstack/animal-kingdom#513]
https://laughing-tesla-a26008.netlify.com

karansag.id.blockstack

**Comment by moxiegirl** [comment]
@karansag Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.


Subway it is!
