### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by pjklein** [blockstack/animal-kingdom#519]
https://peaceful-wescoff-8bd2f0.netlify.com

pjklein_.id.blockstack

**Comment by moxiegirl** [comment]
@pjklein Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Big city view!
