### ISSUE TITLE
hey add my clan ! we chill 

### ISSUE THREAD

**Issue by lddorse** [blockstack/animal-kingdom#520]
https://goofy-agnesi-9a539b.netlify.com/me

leodamiandorsey.id.blockstack

**Comment by moxiegirl** [comment]
@lddorse Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
