### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Hritik14** [blockstack/animal-kingdom#522]
https://frosty-davinci-f19d7e.netlify.com/
hrtkhrtk.id.blockstack

**Comment by moxiegirl** [comment]
@Hritik14 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
