### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ZachHoskins** [blockstack/animal-kingdom#523]
https://keen-jepsen-7a5d1a.netlify.com/

zachhoskins.id.blockstack

**Comment by moxiegirl** [comment]
@ZachHoskins Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
