### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by citrustux** [blockstack/animal-kingdom#524]
https://happy-aryabhata-011484.netlify.com/

citrustux.id

**Comment by moxiegirl** [comment]
@citrustux Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
