### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by jazbogross** [blockstack/animal-kingdom#525]
https://angry-noether-618c3e.netlify.com/

jazbogross.id.blockstack

**Comment by moxiegirl** [comment]
@jazbogross Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Why so much drinking?
