### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by darrel-pol** [blockstack/animal-kingdom#526]
https://angry-hopper-791a28.netlify.com/

darrelpol.id.blockstack

**Comment by moxiegirl** [comment]
@darrel-pol Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
