### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by mcorossigo** [blockstack/animal-kingdom#527]
https://animal-kingdom.matteocorossigo95.now.sh/

mcorossigo.id.blockstack

**Comment by moxiegirl** [comment]
@mcorossigo Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
