### ISSUE TITLE
Please add my Kingdom to your Clan

### ISSUE THREAD

**Issue by wushuwei** [blockstack/animal-kingdom#528]
https://festive-shaw-b23343.netlify.com/

wushuwei.id.blockstack

**Comment by moxiegirl** [comment]
@wushuwei  Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
