### ISSUE TITLE
Please add my Kingdom to your clan!

### ISSUE THREAD

**Issue by jpvajda** [blockstack/animal-kingdom#529]
https://blockstack-animal-kingdom.netlify.com/

kratosjv.id.blockstack

**Comment by moxiegirl** [comment]
@jpvajda Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Spacey!

**Comment by jpvajda** [comment]
@moxiegirl Thank you!
