### ISSUE TITLE
Please add my New Kingdom to your clan...

### ISSUE THREAD

**Issue by BeastieBots** [blockstack/animal-kingdom#53]
https://confident-northcutt-143b95.netlify.com

natthecat.id.blockstack

:)

**Comment by moxiegirl** [comment]
@BeastieBots Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
