### ISSUE TITLE
Please add my kingdom to my clan!

### ISSUE THREAD

**Issue by servatj** [blockstack/animal-kingdom#530]
https://kind-wilson-d5a196.netlify.com

josepservatlorca.id.blockstack

**Comment by moxiegirl** [comment]
@servatj Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
