### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by illusioncoder7** [blockstack/animal-kingdom#542]
https://admiring-mclean-519468.netlify.com

ibrizshubham.id.blockstack

**Comment by moxiegirl** [comment]
@illusioncoder7 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
