### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by evrardts** [blockstack/animal-kingdom#543]
https://epic-euler-b978c9.netlify.com/me

evrardts.id.blockstack

**Comment by moxiegirl** [comment]
@evrardts Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
