### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by zyra-zia** [blockstack/animal-kingdom#544]
https://blockstackanimalkingdom.web.app/kingdom/zyra_zia.id.blockstack

zyra_zia.id.blockstack

**Comment by moxiegirl** [comment]
@zyra-zia Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
