### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by phNam2** [blockstack/animal-kingdom#545]
https://nifty-brown-9ec8e2.netlify.com

nampham97.id.blockstack

**Comment by moxiegirl** [comment]
@phNam2 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
