### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by dnorton94** [blockstack/animal-kingdom#546]
https://elegant-torvalds-f4acec.netlify.com

dominiconorton.id.blockstack

**Comment by moxiegirl** [comment]
@dnorton94 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
