### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by naszam** [blockstack/animal-kingdom#547]
https://quirky-lewin-0d1739.netlify.com/

nazzareno.id.blockstack

**Comment by moxiegirl** [comment]
@naszam  Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
