### ISSUE TITLE
Unable to build ubuntu 18.04

### ISSUE THREAD

**Issue by cryptobabel** [blockstack/animal-kingdom#55]
Failed to minify the code from this file: 

 	./node_modules/key-encoder/node_modules/asn1.js/lib/asn1/decoders/der.js:58 

Read more here: http://bit.ly/2tRViJ9

npm ERR! Linux 4.15.0-43-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! animal-kingdom@1.0.0-alpha.2 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!

**Comment by moxiegirl** [comment]
@cryptobabel  Sorry to hear there is a problem on Ubuntu.  One of our users just updated the code around minify with a pull request.  Would you like to download or update your code and give it a test? It fixed my Windows minify issues.

**Comment by cryptobabel** [comment]
I will take a gander. Thanks for the update. I completely rebuilt vms as i thought this might have been a 16.04 issue. Not incredibly familiar with the node world. I'll spin up and report back.

**Comment by cryptobabel** [comment]
Excellent! As of 2ba0c98f645e48a84d944c7694141dc278be6176 I can build. Closing issue as resolved. 

Thank you

**Comment by moxiegirl** [comment]
@cryptobabel Woot! Thank you for the testing.
