### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Franzferdinan51** [blockstack/animal-kingdom#551]
https://fervent-goldberg-29d1f7.netlify.com/

franzferdinan51.id.blockstack

**Comment by moxiegirl** [comment]
@Franzferdinan51 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
