### ISSUE TITLE
Please add my kingdom to your clan!!!

### ISSUE THREAD

**Issue by Hrtkk** [blockstack/animal-kingdom#554]
https://confident-spence-82e7d4.netlify.com
hritikkumar.id.blockstack

**Comment by moxiegirl** [comment]
@Hrtkk Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
