### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by BAGPALLAB7** [blockstack/animal-kingdom#555]
https://flamboyant-darwin-394e11.netlify.com/me

bagpallab7.id.blockstack

**Comment by moxiegirl** [comment]
@BAGPALLAB7 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
