### ISSUE TITLE
add my kingdom to your clan

### ISSUE THREAD

**Issue by vital-edu** [blockstack/animal-kingdom#556]
https://flamboyant-kare-0698a3.netlify.com/

eduardovital.id.blockstack

**Comment by moxiegirl** [comment]
@vital-edu Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
