### ISSUE TITLE
Please add my kingdom to the Blockstack demo app clan !

### ISSUE THREAD

**Issue by apanait** [blockstack/animal-kingdom#558]
https://mystifying-lamport-3870ac.netlify.com
andpanait.id.blockstack

**Comment by moxiegirl** [comment]
@apanait Waves! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
