### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by dyoungwd** [blockstack/animal-kingdom#559]
https://tuxverse.runkodapps.com/

dyoungwd.id.blockstack

**Comment by moxiegirl** [comment]
@dyoungwd You really up-tux'd the sample. Good job.

Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
