### ISSUE TITLE
Add my kingdom please

### ISSUE THREAD

**Issue by Taylor4484** [blockstack/animal-kingdom#560]
https://dreamy-hugle-033503.netlify.com/

digitalsaas.id.blockstack

**Comment by moxiegirl** [comment]
@Taylor4484 Austin! Former Austinite here...power on! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
