### ISSUE TITLE
Behold the Kingdom of Westeros in BlockStack

### ISSUE THREAD

**Issue by GeekBoySupreme** [blockstack/animal-kingdom#561]
https://westeros011.netlify.com/

distorted_aura.id.blockstack

**Comment by moxiegirl** [comment]
@GeekBoySupreme --- you are indeed supreme! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
