### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ankur-kayal** [blockstack/animal-kingdom#562]
https://naughty-hypatia-646ad8.netlify.com

ankurkayal.id.blockstack

**Comment by moxiegirl** [comment]
@ankur-kayal Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
