### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Pratap2018** [blockstack/animal-kingdom#563]
https://elated-mayer-4f242d.netlify.com/

pratapmridha.id.blockstack

**Comment by moxiegirl** [comment]
@Pratap2018 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
