### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ericckk** [blockstack/animal-kingdom#564]
https://cocky-tesla-b0793a.netlify.com

simplistic_username.id.blockstack

**Comment by moxiegirl** [comment]
@ericckk Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
