### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by marcomariscal** [blockstack/animal-kingdom#567]
https://sleepy-clarke-8f5ecb.netlify.com/

marcomariscal.id.blockstack

**Comment by moxiegirl** [comment]
@marcomariscal Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
