### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by chinkusimon** [blockstack/animal-kingdom#568]
https://nostalgic-fermi-5d0239.netlify.com

chinkusimon.id.blockstack

**Comment by moxiegirl** [comment]
@chinkusimon Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

I like the map!
