### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by viraj124** [blockstack/animal-kingdom#569]
https://angry-villani-07efa1.netlify.com/kingdom/viraz1996.id.blockstack

viraz1996.id.blockstack

**Comment by moxiegirl** [comment]
@viraj124 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
