### ISSUE TITLE
Please add my kingdom to your clan! 

### ISSUE THREAD

**Issue by mingir2** [blockstack/animal-kingdom#571]
https://mingiryu-animal-kingdom.netlify.com/

mingiryu.id.blockstack

**Comment by moxiegirl** [comment]
@mingir2 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
