### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by hadlocna** [blockstack/animal-kingdom#572]
https://sharp-swartz-391b26.netlify.com
leinahtan.id.blockstack

**Comment by moxiegirl** [comment]
@hadlocna welcome to the kingdom of Ohio! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
