### ISSUE TITLE
Please add my kingdom to your clan~

### ISSUE THREAD

**Issue by caosbad** [blockstack/animal-kingdom#574]
https://clever-dijkstra-fdab4d.netlify.com/kingdom/whoisyourdaddy.id.blockstack

whoisyourdaddy.id.blockstack

**Comment by moxiegirl** [comment]
@caosbad Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
