### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by srhr17** [blockstack/animal-kingdom#575]
https://distracted-albattani-288b8b.netlify.com

srihari17.id.blockstack

**Comment by moxiegirl** [comment]
@srhr17 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
