### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by quilldata** [blockstack/animal-kingdom#577]
https://pensive-heyrovsky-740c31.netlify.com

hackmyway.id.blockstack

**Comment by moxiegirl** [comment]
@quilldata Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by quilldata** [comment]
Hi,



Thank you!

I have already submitted my dApp on app.co.



Thank You

Abhay



---- On Tue, 07 Jan 2020 08:58:15 +0530 Moxiegirl <notifications@github.com> wrote ----


https://github.com/quilldata Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
