### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by MichelLeideson-Pain** [blockstack/animal-kingdom#578]
https://gracious-panini-8bd70c.netlify.com

mlgsistema.id.blockstack

**Comment by moxiegirl** [comment]
@MichelLeideson-Pain Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
