### ISSUE TITLE
Please add my kingdom to your clan..

### ISSUE THREAD

**Issue by mharley12345** [blockstack/animal-kingdom#579]
https://amazing-mcclintock-754a17.netlify.com
mharley12345.id.blockstack

**Comment by moxiegirl** [comment]
@markmhx Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
