### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by CosmicNode13** [blockstack/animal-kingdom#580]
https://tender-cori-43d4b4.netlify.com/

cosmicnode13.id.blockstack

**Comment by moxiegirl** [comment]
@CosmicNode13 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
