### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by GueTorres** [blockstack/animal-kingdom#581]
https://eager-wright-71bbe6.netlify.com

guetorresdev.id.blockstack

**Comment by moxiegirl** [comment]
@GueTorres Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
