### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by tech9990** [blockstack/animal-kingdom#582]
https://trusting-dubinsky-b3e5c8.netlify.com/

distinval.id.blockstack

**Comment by moxiegirl** [comment]
@tech9990 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
