### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by freedom-is-coming** [blockstack/animal-kingdom#584]
https://wizardly-liskov-0c023d.netlify.com/kingdom/freedom_is_coming.id.blockstack

freedom_is_coming.id.blockstack

**Comment by moxiegirl** [comment]
@freedom-is-coming Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
