### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by Gauravsaha-97** [blockstack/animal-kingdom#588]
https://nostalgic-pike-88dadc.netlify.com
gaurav97.id.blockstack

**Comment by moxiegirl** [comment]
@Gauravsaha-97 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
