### ISSUE TITLE
 Please add my kingdom to your clan

### ISSUE THREAD

**Issue by waynenilsen** [blockstack/animal-kingdom#589]
https://competent-wescoff-4358d1.netlify.com/

waynenilsen.id.blockstack

**Comment by moxiegirl** [comment]
@waynenilsen Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
