### ISSUE TITLE
Add my kingdom?

### ISSUE THREAD

**Issue by cdsattelmayer** [blockstack/animal-kingdom#590]
https://zen-newton-b5c0d3.netlify.com/

cdsattelmayer.id.blockstack

**Comment by moxiegirl** [comment]
@cdsattelmayer Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
