### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Fbomont** [blockstack/animal-kingdom#592]
https://musing-ramanujan-1af04b.netlify.com

fbo520741.id.blockstack

**Comment by moxiegirl** [comment]
@Fbomont Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by moxiegirl** [comment]
@Fbomont Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
