### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by walidmujahid** [blockstack/animal-kingdom#593]
https://zealous-leavitt-f06036.netlify.com/

walidmujahid.id.blockstack

**Comment by moxiegirl** [comment]
@walidmujahid Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by moxiegirl** [comment]
@walidmujahid Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by walidmujahid** [comment]
@moxiegirl Thank you. I have submitted it already app.co
