### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Jufi-101** [blockstack/animal-kingdom#594]
https://vigilant-babbage-4c23b7.netlify.com/

mkoltdenny.id.blockstack

**Comment by moxiegirl** [comment]
@Jufi-101 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
