### ISSUE TITLE
Please add my kingdom to your clan !

### ISSUE THREAD

**Issue by imrishabh18** [blockstack/animal-kingdom#596]
https://clever-noether-57ae87.netlify.com

imrishabh18.id.blockstack

**Comment by moxiegirl** [comment]
@imrishabh18 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
