### ISSUE TITLE
please add my kingdom to your clan

### ISSUE THREAD

**Issue by pwarole** [blockstack/animal-kingdom#598]
https://blissful-curran-8475b6.netlify.com

pawanwarole.id.blockstack

**Comment by moxiegirl** [comment]
@pwarole Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
