### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ValentinFromSpace** [blockstack/animal-kingdom#6]
https://valsanimalkingdom.netlify.com

valentin.blackstack.id

**Comment by moxiegirl** [comment]
@ValentinFromSpace Hi, I've added your kingdom but ran into an unexpected problem in our sample. We are working on it. I'm going to leave this open until your kingdom appears in our clan. Thank you for submitting...and go ahead and register for the tshirt!

**Comment by moxiegirl** [comment]
Your kingdom was added but it shows as under siege: mhttps://animalkingdoms.netlify.com/others . While your site is reachable, it appears [Gaia is unable to find your ID](https://explorer.blockstack.org).  Please file an issue if you think this is in error.

Thank you for taking part in the tutorial. Don't forget to add your app to [App.co](https://app.co/) you can do this even when your kingdom is under siege!
