### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by rickmanelius** [blockstack/animal-kingdom#60]
https://modest-chandrasekhar-0e9f62.netlify.com

ID-1MhuTmakatYQR9tUF2ThtQ9woeCY92eWks

**Comment by moxiegirl** [comment]
@rickmanelius Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Snake and desert was a neat add!
