### ISSUE TITLE
 Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by HAKRSINGH** [blockstack/animal-kingdom#601]
https://quizzical-tesla-9181e1.netlify.com

adityavardhansingh.id.blockstack

**Comment by moxiegirl** [comment]
@HAKRSINGH Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
