### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by mohit23x** [blockstack/animal-kingdom#604]
https://quizzical-austin-c21cb0.netlify.com/

mohit23x.id.blockstack

**Comment by moxiegirl** [comment]
@mohit23x Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
