### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by yashpatel12** [blockstack/animal-kingdom#605]
https://wonderful-bhabha-6a5186.netlify.com

yashudev.id.blockstack

**Comment by moxiegirl** [comment]
@yashpatel12 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
