### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by aayushbisen** [blockstack/animal-kingdom#607]
https://serene-dijkstra-749ad1.netlify.com/

aayushbisen.id.blockstack

**Comment by moxiegirl** [comment]
@aayushbisen Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
