### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by anon6405** [blockstack/animal-kingdom#608]
https://serene-mcnulty-4a8fb1.netlify.com/

anon6405.id.blockstack

**Comment by moxiegirl** [comment]
@anon6405 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
