### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Siddhant356** [blockstack/animal-kingdom#609]
https://eager-noyce-825eb9.netlify.com/

siddhant356.id.blockstack

**Comment by moxiegirl** [comment]
@Siddhant356 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
