### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by nayane95** [blockstack/animal-kingdom#612]
https://distracted-panini-8cc564.netlify.com

nayanajith.id.blockstack

**Comment by moxiegirl** [comment]
@nayane95 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
