### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by suijaa** [blockstack/animal-kingdom#613]
https://musing-wiles-d5ff5f.netlify.com

nishith13.id.blockstack

**Comment by moxiegirl** [comment]
@suijaa Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
