### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by dewanshrawat15** [blockstack/animal-kingdom#614]
https://quizzical-raman-c95f4d.netlify.com/

dewanshrawat15.id.blockstack

**Comment by moxiegirl** [comment]
@dewanshrawat15 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by dewanshrawat15** [comment]
@moxiegirl I have added my app.co
Till when can I expect a correspondance to claim my Zero-to-Dapp t-shirt ?

**Comment by moxiegirl** [comment]
@dewanshrawat15 you should get an email this week telling you where you can get your shirt.
