### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by amy-byte** [blockstack/animal-kingdom#615]
https://affectionate-easley-5c3872.netlify.com

amyzhangtt.id.blockstack

**Comment by moxiegirl** [comment]
@amy-byte Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
