### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by parthpandyappp** [blockstack/animal-kingdom#618]
parthpandyappp.netlify.com
parthpandyappp.id.blockstack

**Comment by moxiegirl** [comment]
@parthpandyappp Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by parthpandyappp** [comment]
Hello there,
This is to inform you that I haven't got my T-shirt yet! While others in
India have got'em. I guess that may be a fault of yours or something else?
Please process the request, if possible. I hope you wouldn't at all be
skipping my shipment. Also, it's not like I'm losing my patience, but it
was just a query cum confusion which I wanted to be cleared. It's okay till
the situation
