### ISSUE TITLE
Please add my kingdom to your domain

### ISSUE THREAD

**Issue by zen2see** [blockstack/animal-kingdom#619]
https://trusting-beaver-078a16.netlify.com

zblockstack.id.blockstack

**Comment by moxiegirl** [comment]
@zen2see Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
