### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by indra8981** [blockstack/animal-kingdom#625]
https://ecstatic-perlman-131b80.netlify.com/

codingalways.id.blockstack

**Comment by moxiegirl** [comment]
@indra8981 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
