### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by cTxplorer** [blockstack/animal-kingdom#626]
https://angry-swartz-d2b25c.netlify.com/

pgxplorer.id.blockstack

**Comment by moxiegirl** [comment]
@cTxplorer Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
