### ISSUE TITLE
Would like to add my Kingdom to the Clan 

### ISSUE THREAD

**Issue by NileshArnaiya** [blockstack/animal-kingdom#627]
https://curatedyoutube.netlify.com/

sundarpichai.id.blockstack

**Comment by NileshArnaiya** [comment]
Hi is this added? would like to know the status, thank you

**Comment by moxiegirl** [comment]
@NileshArnaiya Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
