### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by Akshat0410** [blockstack/animal-kingdom#628]
https://zealous-kepler-68ac4d.netlify.com/me

anupamakshat0410.id.blockstack

**Comment by moxiegirl** [comment]
@Akshat0410 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
