### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by samjwu** [blockstack/animal-kingdom#629]
https://trusting-nobel-3b4921.netlify.com/

samjwu1000.id.blockstack

**Comment by moxiegirl** [comment]
@samjwu Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
