### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by Mayankjha997** [blockstack/animal-kingdom#630]
https://affectionate-hugle-3959ea.netlify.com/

mayankjha997@gmail.com

**Comment by moxiegirl** [comment]
@Mayankjha997 I actually need your blockstack Id not your email. Can you give me your blockstack id?

**Comment by Mayankjha997** [comment]
My blockstack id is - major_tangomj.id.blockstack

**Comment by moxiegirl** [comment]
@Mayankjha997 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
