### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by GuyKh** [blockstack/animal-kingdom#631]
https://practical-heyrovsky-0c7eec.netlify.com

guykhmel.id.blockstack

**Comment by moxiegirl** [comment]
@GuyKh Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
