### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by anuragjha** [blockstack/animal-kingdom#633]
https://thirsty-chandrasekhar-6835a4.netlify.com

anuragjha.id.blockstack

**Comment by moxiegirl** [comment]
@anuragjha Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
