### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by lex111** [blockstack/animal-kingdom#634]
https://youthful-brattain-6e2100.netlify.com/

lex111__.id.blockstack

**Comment by moxiegirl** [comment]
@lex111 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
