### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by mbareford** [blockstack/animal-kingdom#635]
https://cocky-franklin-7e9416.netlify.com

mbareford.id.blockstack

**Comment by moxiegirl** [comment]
@mbareford Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
