### ISSUE TITLE
Please add me to your kingdom!!!

### ISSUE THREAD

**Issue by mpereannor** [blockstack/animal-kingdom#636]
https://thirsty-leakey-dc4a67.netlify.com/kingdom/mpereannor.id.blockstack

mpereannor.id.blockstack

**Comment by moxiegirl** [comment]
@mpereannor Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
