### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by yozaam** [blockstack/animal-kingdom#637]
https://frosty-brahmagupta-fcf317.netlify.com

0xyozaam.id.blockstack

PS, Love the blockstack web UI !

**Comment by moxiegirl** [comment]
@yozaam Glad you like the UI and thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
