### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by baconmanic** [blockstack/animal-kingdom#638]
https://awesome-ardinghelli-23e0d9.netlify.com

baconmanic.id.blockstack

**Comment by moxiegirl** [comment]
@baconmanic Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by baconmanic** [comment]
I have already done this, but have not heard anything just yet. Can someone
verify?
