### ISSUE TITLE
please add my kingdom to our clan

### ISSUE THREAD

**Issue by Chayan-19** [blockstack/animal-kingdom#639]
https://epic-lalande-57a6c8.netlify.com

chayan19.id.blockstack

**Comment by moxiegirl** [comment]
@Chayan-19 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
