### ISSUE TITLE
please add my kingdom to your clan

### ISSUE THREAD

**Issue by soulreapermxi** [blockstack/animal-kingdom#640]
https://epic-liskov-b9b35e.netlify.com

soulreapermxi619.id.blockstack

**Comment by moxiegirl** [comment]
@soulreapermxi Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
