### ISSUE TITLE
Add my kingdom to clan please

### ISSUE THREAD

**Issue by jaswalabhijeet** [blockstack/animal-kingdom#641]
https://practical-einstein-6d63c5.netlify.com
abhijeetjaswal2704.id.blockstack

**Comment by moxiegirl** [comment]
@jaswalabhijeet Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
