### ISSUE TITLE
Please add my kingdom to my clan!

### ISSUE THREAD

**Issue by crashoverloaded** [blockstack/animal-kingdom#642]
https://flamboyant-davinci-74a77f.netlify.com

crashoverloaded.id.blockstack

**Comment by moxiegirl** [comment]
@crashoverloaded Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
