### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Gkthakare** [blockstack/animal-kingdom#643]
https://jovial-montalcini-714a37.netlify.com/

gk_intruder.id.blocstacks

**Comment by moxiegirl** [comment]
@Gkthakare Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
