### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Rounik10** [blockstack/animal-kingdom#644]
New To Animal Kingdom
https://romantic-mclean-1a0335.netlify.com/

Block Stack ID : rounik2000.id.blockstack
ID-14zMZpxRBvTDggPHqSbg33M57kvPjiYFzW

**Comment by moxiegirl** [comment]
@Rounik10 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
