### ISSUE TITLE
Please add my kindom to your clan!

### ISSUE THREAD

**Issue by ryokugyu** [blockstack/animal-kingdom#645]
https://hopeful-nightingale-e1d1c5.netlify.com

**Comment by moxiegirl** [comment]
@ryokugyu Can you supply your blockstack id? I need that to add you to the clan.

**Comment by ryokugyu** [comment]
ryokugyu.blockstack.id

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
