### ISSUE TITLE
Please add my kingdom to our clan!

### ISSUE THREAD

**Issue by arjun1311** [blockstack/animal-kingdom#646]
https://youthful-ride-899c28.netlify.com

soulbk201.id.blockstack

**Comment by moxiegirl** [comment]
@arjun1311 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
