### ISSUE TITLE
Add my kingdom to your clan, noble subjects!

### ISSUE THREAD

**Issue by utkarshsingh99** [blockstack/animal-kingdom#647]
https://this-is-my-kingdom-come.netlify.com/kingdom/utkarshsingh99.id.blockstack

utkarshsingh99.id.blockstack

**Comment by moxiegirl** [comment]
@utkarshsingh99 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
