### ISSUE TITLE
please add my kindom to your clan

### ISSUE THREAD

**Issue by achilleas96** [blockstack/animal-kingdom#648]
https://inspiring-brown-e28ea8.netlify.com

yurogini.id.blockstack

**Comment by moxiegirl** [comment]
@achilleas96 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
