### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by sriniketh28** [blockstack/animal-kingdom#649]
https://agitated-volhard-be8cc0.netlify.com/me

sriniketh.id.blockstack

**Comment by moxiegirl** [comment]
@sriniketh28 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
