### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by bartonhammond** [blockstack/animal-kingdom#65]
https://hopeful-mcclintock-559a85.netlify.com

bartonij.id.blockstack

**Comment by moxiegirl** [comment]
@bartonhammond  Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by bartonhammond** [comment]
Hi - I already completed the Tutorial and submitted it to app.co

Im looking forward to the free T-shirt

**Comment by moxiegirl** [comment]
@bartonhammond Wonderful, you should be receiving an email with instructions within the next few days.  Hope you enjoy the t-shirt, we get a kick out of it.
