### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by pereiraryan** [blockstack/animal-kingdom#650]
https://cranky-pike-449f21.netlify.com/

ryanpereira.id.blockstack

**Comment by moxiegirl** [comment]
@pereiraryan Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
