### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Kumar82098** [blockstack/animal-kingdom#651]
https://naughty-brown-459b00.netlify.com

kchaman101.id.blockstack

**Comment by moxiegirl** [comment]
@Kumar82098 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
