### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Logan1x** [blockstack/animal-kingdom#652]
https://angry-yonath-ab833f.netlify.com/

logan11x.id.blockstack

**Comment by moxiegirl** [comment]
@Logan1x Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
