### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by monizb** [blockstack/animal-kingdom#653]
https://infallible-shockley-36179e.netlify.com/

monishbasaniwal2.id.blockstack

**Comment by moxiegirl** [comment]
@monizb Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
