### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by abhi2196** [blockstack/animal-kingdom#654]
https://abhishek-kingdom.netlify.com
abhishek_21.id.blockstack

Thanks

**Comment by moxiegirl** [comment]
@abhi2196 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
