### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by gunjanmimo** [blockstack/animal-kingdom#655]
https://vibrant-lewin-26df0b.netlify.com

gunjanmimo.id.blockstack

**Comment by moxiegirl** [comment]
@gunjanmimo Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
