### ISSUE TITLE
New Issue Centipede

### ISSUE THREAD

**Issue by Rounik10** [blockstack/animal-kingdom#656]
New Contribution 
https://gracious-bartik-1c9621.netlify.com/

rounik.2000.id.blockstack

**Comment by moxiegirl** [comment]
@Rounik10 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
