### ISSUE TITLE
Add my Kingdom to the Clan, BlockStack Fam!

### ISSUE THREAD

**Issue by sudiptog81** [blockstack/animal-kingdom#657]
https://gallant-hamilton-88496c.netlify.com/

sudiptoghosh.id.blockstack

**Comment by moxiegirl** [comment]
@sudiptog81 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
