### ISSUE TITLE
Add my kingdom to your clan 

### ISSUE THREAD

**Issue by sahilister** [blockstack/animal-kingdom#658]
https://sleepy-knuth-b518f4.netlify.com/

mukebaaj.id.blockstack

**Comment by moxiegirl** [comment]
@sahilister Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
