### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by bradyisom** [blockstack/animal-kingdom#66]
https://hopeful-lamport-75d72a.netlify.com

bradyisom.id.blockstack

**Comment by renegmed** [comment]
https://world-needs-animals.netlify.com

renegmed.id.blockstack

**Comment by moxiegirl** [comment]
@bradyisom @renegmed Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
