### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Vedaant-Rajoo** [blockstack/animal-kingdom#660]
https://affectionate-boyd-605ffb.netlify.com/

newedia12.id.blockstack

**Comment by moxiegirl** [comment]
@Vedaant-Rajoo Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
