### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by chayan-chawra** [blockstack/animal-kingdom#661]
https://relaxed-mccarthy-5a3e40.netlify.com

prapti05.id.blockstack

**Comment by moxiegirl** [comment]
@chayan-chawra Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
