### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Suchana34** [blockstack/animal-kingdom#662]
https://xenodochial-booth-b5ef9e.netlify.com

suchanablocky.id.blockstack

**Comment by moxiegirl** [comment]
@Suchana34 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
