### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by sspeedy99** [blockstack/animal-kingdom#663]
https://jolly-hugle-d4adf8.netlify.com/

sspeedy99.id.blockstack

**Comment by moxiegirl** [comment]
@sspeedy99 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
