### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by S-ayanide** [blockstack/animal-kingdom#664]
https://suspicious-elion-bb2fd5.netlify.com/

sayanide.id.blockstack

**Comment by moxiegirl** [comment]
@S-ayanide Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
