### ISSUE TITLE
add kingdom

### ISSUE THREAD

**Issue by Mmaarten23** [blockstack/animal-kingdom#667]
https://modest-jepsen-14194c.netlify.com/

mmaarten.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
