### ISSUE TITLE
Please add my kingdom to your clan! (before the dragons arrive to Westeros)

### ISSUE THREAD

**Issue by parasg1999** [blockstack/animal-kingdom#668]
elated-khorana-4e3544.netlify.com

parasg1999.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
