### ISSUE TITLE
Please add my clan !

### ISSUE THREAD

**Issue by Sidhanthsur** [blockstack/animal-kingdom#670]
https://quizzical-jang-1ffac1.netlify.com

sidhanth.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
