### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by singhharsh998** [blockstack/animal-kingdom#673]
https://naughty-bardeen-60fe73.netlify.com

singhharsh998.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
