### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ishanvj2207** [blockstack/animal-kingdom#675]
https://upbeat-turing-7ecf94.netlify.com/

voldemort2207.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by panda311** [comment]
Hey !! I already have filled the form like 2 weeks ago but haven't received any info on it yet .
Can you tell me proceedings for it.

**Comment by ishanvj2207** [comment]
Hey !! I already have filled the form like 2 weeks ago but haven't received any info on it yet .
Can you tell me proceedings about how to get the t-shirt...
