### ISSUE TITLE
Please add my Kingdom to your clan

### ISSUE THREAD

**Issue by Harshsngh07** [blockstack/animal-kingdom#680]
https://practical-stonebraker-b2388a.netlify.com

harshsngh07.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
