### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by sahil9001** [blockstack/animal-kingdom#685]
https://blissful-cray-9f4506.netlify.com/

sahil9004.id.blockstack

**Comment by sahil9001** [comment]
Can I get updates on the status of this issue? When will it get merged?

**Comment by moxiegirl** [comment]
@sahil9001 we allow these issues to accumulate and merge on a weekly basis. You don't have to wait for a merge to submit your sample to app.co

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
