### ISSUE TITLE
Please add my kingdom to your clan.

### ISSUE THREAD

**Issue by Ayu-Raj** [blockstack/animal-kingdom#688]
https://unruffled-lamport-ac3474.netlify.com

ayush_10.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
