### ISSUE TITLE
Please add my Kingdom to your clan!

### ISSUE THREAD

**Issue by pratiknoubagh** [blockstack/animal-kingdom#689]
https://ecstatic-hoover-8ffffc.netlify.com/

pratik23noubagh.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
