### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by jaboynton** [blockstack/animal-kingdom#69]
https://optimistic-wing-7a17ab.netlify.com

jamersden.id.blockstack

**Comment by moxiegirl** [comment]
@jaboynton  Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
