### ISSUE TITLE
New kindom with hyperspace terrains!!!!!

### ISSUE THREAD

**Issue by Suyyashaa** [blockstack/animal-kingdom#690]
https://affectionate-liskov-0f1445.netlify.com/
suyasha_.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by Suyyashaa** [comment]
Hello,
I have already submitted my animal kingdom on app.co about a week ago, but
have received no information about the T-shirt. Can I please be informed as
to what should I do next to claim my T-shirt?
Thank you.
