### ISSUE TITLE
Please add my wonderful Kingdom to your Clan! 

### ISSUE THREAD

**Issue by kingmoc** [blockstack/animal-kingdom#692]
https://silly-northcutt-86b201.netlify.com/

kingmoc1.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
