### ISSUE TITLE
Please add my kinkdom to your clan!

### ISSUE THREAD

**Issue by jdu74** [blockstack/animal-kingdom#696]
https://lucid-austin-479388.netlify.com

jeandurieux.id

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
