### ISSUE TITLE
please add my kingdom to your clan

### ISSUE THREAD

**Issue by sparkingdark** [blockstack/animal-kingdom#698]
https://angry-heisenberg-cda945.netlify.com/

helloworld2345.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by sparkingdark** [comment]
Already done....
