### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by kkomaz** [blockstack/animal-kingdom#7]
https://elastic-yalow-5d7c5a.netlify.com

kkomaz.blackstack.id

**Comment by moxiegirl** [comment]
@kkomaz Hi, I've added your kingdom but ran into an unexpected problem in our sample. We are working on it.  I'm going to leave this open until your kingdom appears in our clan. Thank you for submitting...and go ahead and register for the tshirt!

**Comment by moxiegirl** [comment]
@kkomaz Your kingdom was added but it shows as under siege. While your site is reachable, it appears [our explorer is unable to find your ID registered](https://explorer.blockstack.org).  Please file an issue if you think this is in error.

https://github.com/blockstack/blockstack-explorer
