### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by Nasir-Eqbal** [blockstack/animal-kingdom#70]
https://silly-easley-34c111.netlify.com/me
nasireqbal.id.blockstack

**Comment by moxiegirl** [comment]
@Nasir-Eqbal Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by moxiegirl** [comment]
@Nasir-Eqbal Love the microbes! Cool idea.

**Comment by Nasir-Eqbal** [comment]
I a not able to browse  https://animalkingdoms.netlify.com/others, page is always redirected to 
https://animalkingdoms.netlify.com/me.

**Comment by moxiegirl** [comment]
@Nasir-Eqbal Thank you for the report. I'm looking into it.

**Comment by moxiegirl** [comment]
@Nasir-Eqbal So, I think I understand what is happening. This animal kingdom is an entirely new application from your own. YOu need to create an animal/territory combination for your ID in *this* instance. Then, once you do that, you'll be able to visit the other pages.

**Comment by Nasir-Eqbal** [comment]
thanks for fixing routing issue, when i am looking for my application i can see following

Is the planet https://silly-easley-34c111.netlify.com/me under siege?

What does it mean?

How do i activate my application. I followed the step to host the application on App.Co
________________________________

**Comment by moxiegirl** [comment]
@Nasir-Eqbal This is solved.  The URL you submitted include the `/me` path. After removing this, it worked fine.
