### ISSUE TITLE
Please add my kindgdom to your clan!

### ISSUE THREAD

**Issue by ssvas1997** [blockstack/animal-kingdom#700]
https://goofy-leakey-e0603d.netlify.com

ssvas1997s.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
