### ISSUE TITLE
New kingdom, Add to clan

### ISSUE THREAD

**Issue by jayrajroshan** [blockstack/animal-kingdom#703]
https://gracious-knuth-452520.netlify.com/

jayrajroshan.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
