### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by i-Rony** [blockstack/animal-kingdom#706]
https://stoic-stonebraker-0958bb.netlify.com

i_am_rony.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
