### ISSUE TITLE
Please add my kingdom to you clan!

### ISSUE THREAD

**Issue by d-schaffer** [blockstack/animal-kingdom#707]
https://relaxed-bartik-3a06af.netlify.com

dschaffer.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
