### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by lglaves** [blockstack/animal-kingdom#71]
https://friendly-goldwasser-192893.netlify.com

lbglaves.id.blockstack

**Comment by moxiegirl** [comment]
@lglaves Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by moxiegirl** [comment]
@lglaves now that song underthesea is in my ear

![](https://media.giphy.com/media/F2T3P6xnjLRgQ/giphy.gif)
