### ISSUE TITLE
Could you add my kingdom to your?

### ISSUE THREAD

**Issue by MKlblangenois** [blockstack/animal-kingdom#712]
https://awesome-montalcini-cfef56.netlify.com/

lblangenois.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
