### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by AnonProductions** [blockstack/animal-kingdom#714]
https://sankhachak.netlify.com

sankhachak.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by AnonProductions** [comment]
Hey @louiseivan , I have already submitted the sample application to https://app.co but haven't heard from them yet. It has been 6 days. Could you share any updates regarding it?
