### ISSUE TITLE
Please add me to your clan !

### ISSUE THREAD

**Issue by shivansh-narayan** [blockstack/animal-kingdom#717]
https://stoic-yalow-caf53c.netlify.com

shivanshn.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by shivansh-narayan** [comment]
Hi, I have not received any mail for the t-shirt... I have already published my app on app.co
