### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by TheRealTechWiz** [blockstack/animal-kingdom#723]
https://hardcore-curie-4e1578.netlify.com/

therealtechwiz.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by TheRealTechWiz** [comment]
I can't see my app under your other kingdom section. Kindly check if it is added. Also I have submitted my app in app.co but haven't received any mail to claim my tshirt
