### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by dawin123** [blockstack/animal-kingdom#727]
https://hopeful-goldwasser-9c26b8.netlify.com/

dawin123.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
