### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by andrew-healey** [blockstack/animal-kingdom#731]
https://distracted-darwin-75f728.netlify.com

andrewhealey.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by andrew-healey** [comment]
I am having trouble submitting my app to https://app.co. I cannot sign-in with blockstack; whenever I go to https://app.co/submit-your-app, I click "Sign in with Blockstack" and I am redirected to https://browser.blockstack.com, where I give app.co access to my basic information. From there, I am redirected to app.co, where the "Sign in with Blockstack" button is still there. I cannot submit the form, as it tells me that I have not yet signed in. I am considering posting an issue on the repo for app.co. Do you know if I am doing anything wrong? Thanks.

Step 1:
![image](https://user-images.githubusercontent.com/26335275/74381859-45e34700-4dba-11ea-8049-e4b19c985754.png)

Step 2:
![image](https://user-images.githubusercontent.com/26335275/74381886-55629000-4dba-11ea-8ae2-5a6f278b1097.png)

Step 3:
![image](https://user-images.githubusercontent.com/26335275/74381905-601d2500-4dba-11ea-9d47-bc777a8470ad.png)
