### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by yo64-bit** [blockstack/animal-kingdom#734]
https://practical-haibt-e5e0aa.netlify.com

java_boy.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
