### ISSUE TITLE
Please add my Kingdom to your Clan!

### ISSUE THREAD

**Issue by BLJS2warchief** [blockstack/animal-kingdom#741]
https://festive-archimedes-d46712.netlify.com/others

bljs2warchief.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
