### ISSUE TITLE
Pleas add my kingdom to your clan!

### ISSUE THREAD

**Issue by reallyinvincible** [blockstack/animal-kingdom#742]
https://heuristic-mcnulty-c44dc6.netlify.com

sparshsri.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
