### ISSUE TITLE
Please, m'lord, add my colony to your clan

### ISSUE THREAD

**Issue by THKazi** [blockstack/animal-kingdom#744]
https://xenodochial-euler-0f3c96.netlify.com/

\_thkazi\_.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
