### ISSUE TITLE
commandant, please add my nation to your colony!

### ISSUE THREAD

**Issue by ommpatel3** [blockstack/animal-kingdom#745]
https://nervous-northcutt-eedb5c.netlify.com

ommpatel3.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
