### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by olletsoc** [blockstack/animal-kingdom#75]
https://zen-yonath-540268.netlify.com

olletsoc.id

**Comment by moxiegirl** [comment]
@olletsoc Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
