### ISSUE TITLE
Please Add My Kingdom to your clan!

### ISSUE THREAD

**Issue by PrajvalRaval** [blockstack/animal-kingdom#751]
https://vigilant-lamarr-c639a1.netlify.com

prajvalraval.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
