### ISSUE TITLE
Please Add my Animal Kingdom to your Clan

### ISSUE THREAD

**Issue by RishabMangal** [blockstack/animal-kingdom#752]
https://rishabs-animal-kingdom.netlify.com/

rishabmangal.id.blockstate

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
