### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by sharmajatin741** [blockstack/animal-kingdom#756]
https://happy-kalam-431e5b.netlify.com

sharmajatin741.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
