### ISSUE TITLE
Please Add My Kingdom to your clan!

### ISSUE THREAD

**Issue by gorkemozlu** [blockstack/animal-kingdom#757]
https://vibrant-bardeen-9e93b4.netlify.com

gorkemozlu.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
