### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by techno-disaster** [blockstack/animal-kingdom#760]
https://kind-fermi-bfde20.netlify.com

techno_disaster.id.blockstack

**Comment by louiseivan** [comment]
Love the Blockstack ID! Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
