### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by nandakishormpai** [blockstack/animal-kingdom#766]
https://objective-snyder-f2f2ae.netlify.com

nmpai2001.id.bloackstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by nandakishormpai** [comment]
i have submitted and i didn't end up in a page which tells about the
T-Shirt.what to do?
