### ISSUE TITLE
Add me to your esteemed kingdom :D

### ISSUE THREAD

**Issue by adinalini** [blockstack/animal-kingdom#779]
https://pedantic-neumann-9b2243.netlify.com/

adinalini.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
