### ISSUE TITLE
Add me to your kingdom!

### ISSUE THREAD

**Issue by nilay011** [blockstack/animal-kingdom#781]
https://dazzling-payne-6944f6.netlify.com
nilaysharma.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
