### ISSUE TITLE
please add my kingdom in your clan

### ISSUE THREAD

**Issue by Sandeep3231** [blockstack/animal-kingdom#785]
https://romantic-ramanujan-978b08.netlify.com
sy323156.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
