### ISSUE TITLE
please add my kingdom to your clan! :D

### ISSUE THREAD

**Issue by rbgoncalves** [blockstack/animal-kingdom#788]
https://competent-curran-5d19f3.netlify.com/

bldd1997.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
