### ISSUE TITLE
App shows unavailable kingdoms in /others as well

### ISSUE THREAD

**Issue by DhairyaSethi** [blockstack/animal-kingdom#789]
App shows obviously unavailable kingdoms (such as ones on localhost) as well. Not sure if it's intended or not. 
Also, 
https://amazing-wright-e4c08e.netlify.com
fallenderl.id.blockstack

**Comment by louiseivan** [comment]
@DhairyaSethi thanks for noticing it! Some dappers usually deprecate their kingdoms after taking the tutorial for quite some time. Hence, it is the reason for unavailable kingdoms. Anyhow, Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
