### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by jazken** [blockstack/animal-kingdom#79]
https://confident-borg-21283f.netlify.com

jazken.id.blockstack

**Comment by moxiegirl** [comment]
@jazken Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
