### ISSUE TITLE
please add my kingdom to the clan!

### ISSUE THREAD

**Issue by arushikat13** [blockstack/animal-kingdom#791]
https://loving-curie-7cb87c.netlify.com/

arushikat13.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
