### ISSUE TITLE
Please add my kingdom to your clan!!

### ISSUE THREAD

**Issue by r3h3mm** [blockstack/animal-kingdom#795]
https://confident-pare-ad7de7.netlify.com

mehervatsa.id.blackstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by r3h3mm** [comment]
Thanks
