### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Shrey0** [blockstack/animal-kingdom#797]
https://peaceful-colden-293797.netlify.com/

jagadshrey.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by Shrey0** [comment]
Do I have to do any further steps to claim my Zero-to-Dapp t-shirt?

I did not understand why you sent the Colsed#797 mail. Can you please
elaborate.

       SHREY JAGAD

*          Student - Computer Engineering*
*          R.C.Technical Institute, *
*          Ahmedabad.*
