### ISSUE TITLE
Please add my kingdome

### ISSUE THREAD

**Issue by DiegoAngelino** [blockstack/animal-kingdom#80]
https://flamboyant-beaver-c71164.netlify.com

diego_angelino.id.blockstack

**Comment by moxiegirl** [comment]
@DiegoAngelino Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
