### ISSUE TITLE
please add my kingdom to your clan

### ISSUE THREAD

**Issue by farzanfa** [blockstack/animal-kingdom#801]
https://epic-goodall-f0e57e.netlify.com/

farzanfa.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
