### ISSUE TITLE
Please add my kingdom to your clan

### ISSUE THREAD

**Issue by iamsurajdc** [blockstack/animal-kingdom#803]
https://quirky-montalcini-f449bb.netlify.com

curiousneuron.id.blockstack

**Comment by iamsurajdc** [comment]
@louiseivan I request you to look into the issue.
Thank you!

**Comment by louiseivan** [comment]
Thank you for joining our clan! Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by iamsurajdc** [comment]
@louiseivan I already submitted it to app.co but I didn't get the mail yet? May I know the reason, please?
