### ISSUE TITLE
Please Add my Kingdom to your clan

### ISSUE THREAD

**Issue by harshraj22** [blockstack/animal-kingdom#804]
https://cranky-heyrovsky-666b3d.netlify.com/me

harshraj22.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
