### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by bobm123** [blockstack/animal-kingdom#81]
https://trusting-kirch-492433.netlify.com/

rmarchese.id.blockstack

**Comment by moxiegirl** [comment]
@bobm123 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
