### ISSUE TITLE
Please add my new kingdom to your clan!

### ISSUE THREAD

**Issue by c0sm0void** [blockstack/animal-kingdom#811]
https://loving-brown-a6f41a.netlify.com

minnonymous.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
