### ISSUE TITLE
Add this kingdom to blockstack

### ISSUE THREAD

**Issue by Vivek265** [blockstack/animal-kingdom#812]
https://festive-montalcini-fc81f3.netlify.com

vivek265.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
