### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by simran1509** [blockstack/animal-kingdom#818]
https://priceless-aryabhata-3d58cf.netlify.com
astridhofferman.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by simran1509** [comment]
Hello ,
I am writing to you to know about the zerro to dapp t shirt I claimed and I
havent heard from any of your associates after this email regarding the
information of my reward . I hope to hear from you soon . I would like if
you ask me my address and post me about the updates of my t shirt . I loved
the t shirt and that is why I am writing to you .
