### ISSUE TITLE
Please Add My Kingdom to Your Clan

### ISSUE THREAD

**Issue by NicoN00b** [blockstack/animal-kingdom#82]
https://pensive-tereshkova-29c564.netlify.com/

nicon00b.id.blockstack

**Comment by moxiegirl** [comment]
@NicoN00b wonderful kingdom! Love your change.  

Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
