### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by NandakrishnanR** [blockstack/animal-kingdom#824]
https://blissful-nightingale-d5d481.netlify.com/kingdom/nandurnair.id.blockstack
nandurnair.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
