### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by spiritedawayseasong** [blockstack/animal-kingdom#825]
https://serene-brattain-cb202d.netlify.com

kushelnr.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by spiritedawayseasong** [comment]
> Hi I submitted the application, but didn't receive any follow up email.

@louiseivan

**Comment by spiritedawayseasong** [comment]
Thank you! I received my T-Shirt this morning!
