### ISSUE TITLE
Please add to the Kingdom

### ISSUE THREAD

**Issue by GoyalSidhant** [blockstack/animal-kingdom#829]
https://loving-wozniak-23770b.netlify.com

sidhantgoyal.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
