### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ottoman91** [blockstack/animal-kingdom#83]
https://blissful-hodgkin-6062b1.netlify.com 

ottoman91.id.blockstack

**Comment by moxiegirl** [comment]
@ottoman91 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
