### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by AzT3Risk** [blockstack/animal-kingdom#836]
https://hardcore-boyd-786f7b.netlify.com/

souviklu9a8ic.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
