### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by candaceng** [blockstack/animal-kingdom#837]
https://confident-cori-c098df.netlify.com

candaceng.id.blockstack

**Comment by friedger** [comment]
Could you please add an image for Westereos?

**Comment by candaceng** [comment]
Done!

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
