### ISSUE TITLE
Please add my kingdom to your clan! 

### ISSUE THREAD

**Issue by sunr1** [blockstack/animal-kingdom#84]
https://relaxed-ptolemy-1e8668.netlify.com/

beeccc12.id.blockstack

**Comment by moxiegirl** [comment]
@sunr1 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
