### ISSUE TITLE
Add my Kingdom to your Clan

### ISSUE THREAD

**Issue by Lucas-Kohorst** [blockstack/animal-kingdom#840]
https://elated-meninsky-3ae078.netlify.com/

lucaskohorst.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
