### ISSUE TITLE
Please add my kingdom to clan!

### ISSUE THREAD

**Issue by TeodorRussu** [blockstack/animal-kingdom#843]
https://frosty-albattani-823ff1.netlify.com

rusiashka.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
