### ISSUE TITLE
Please add my kingdom to the clan! 

### ISSUE THREAD

**Issue by Neldeborg** [blockstack/animal-kingdom#844]
https://xenodochial-mahavira-8bbd9d.netlify.com/

rasmusknoth.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
