### ISSUE TITLE
please add my animalkingtom to you clan

### ISSUE THREAD

**Issue by vovo999** [blockstack/animal-kingdom#849]
https://vivianzhou.netlify.com/kingdom/2345.id.blockstack
2345.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
