### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by Jas-github** [blockstack/animal-kingdom#85]
https://cranky-bohr-e74e2c.netlify.com/

jas_blockstack.id.blockstack

**Comment by moxiegirl** [comment]
@Jas-github Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
