### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by bhanu-jpg** [blockstack/animal-kingdom#851]
https://gallant-ramanujan-a6fe35.netlify.com/
bhanupratapsingh.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
