### ISSUE TITLE
please add your kingdom to my clan!

### ISSUE THREAD

**Issue by andrewstech** [blockstack/animal-kingdom#853]
https://zoo.andrewstech.me/   #custom domain

andrewstech.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
