### ISSUE TITLE
Please add my Kingdom to your Clan

### ISSUE THREAD

**Issue by AdityaK11** [blockstack/animal-kingdom#856]
https://wonderful-almeida-b1771b.netlify.com

adityakathpalia.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
