### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by flyinspaghetti** [blockstack/animal-kingdom#858]
https://jolly-elion-f900b8.netlify.com/

flyinspaghetti.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by flyinspaghetti** [comment]
Thank you.
How do I claim my free t-shirt?
