### ISSUE TITLE
Please add my kingdom to your clan! 【 •︠ ͜ʖ ︡•】

### ISSUE THREAD

**Issue by qs** [blockstack/animal-kingdom#859]
https://nostalgic-jang-986355.netlify.com/

surrealblocks.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
