### ISSUE TITLE
Please add my Kingdom to your clan!

### ISSUE THREAD

**Issue by cevans109** [blockstack/animal-kingdom#86]
https://epic-kirch-0d81b5.netlify.com/me

rickevans.id.blockstack

**Comment by cevans109** [comment]
Fixed incorrect URL
https://epic-kirch-0d81b5.netlify.com/

rickevans.id.blockstack

**Comment by moxiegirl** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
