### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by bhatipradeep** [blockstack/animal-kingdom#860]
https://vigilant-shirley-e042f4.netlify.com/

pradeep_bhati_bhpradeep.id.blockstack

**Comment by louiseivan** [comment]
Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by bhatipradeep** [comment]
Yes. I have already submitted that long ago I think. Can you check the
submission once whether its completed or not?

*Pradeepsingh Bhati*
B.Tech.( Third Year )
Electronics and Communication Engineering Department,
Sardar Vallabhbhai National Institute of Technology,
Surat, Gujarat, India-395007
