### ISSUE TITLE
Please add my Kingdom to your clan!

### ISSUE THREAD

**Issue by resona8e** [blockstack/animal-kingdom#88]
https://eloquent-shockley-791c49.netlify.com

nate1010.id.blockstack

**Comment by moxiegirl** [comment]
@resona8e Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
