### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by NaliniNong** [blockstack/animal-kingdom#90]
https://youthful-leavitt-0418c0.netlify.com/

mystique.id.blockstack

**Comment by moxiegirl** [comment]
@NaliniNong Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

**Comment by moxiegirl** [comment]
An error in your Kingdom code did end up causing a problem in our clan list. I've removed your kingdom, you won't see it listed in Other Kingdoms. You are still ok to submit your kingdom and receive a tshirt.
