### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by MhmodTayel** [blockstack/animal-kingdom#91]
https://blissful-poitras-112429.netlify.com

mhmodtayel.id.blockstack

**Comment by moxiegirl** [comment]
@MhmodTayel Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.

Love all the animals you added!
