### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by brian501** [blockstack/animal-kingdom#93]
https://adoring-hamilton-e4d10d.netlify.com

brian501.id.blockstack

**Comment by moxiegirl** [comment]
@brian501 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
