### ISSUE TITLE
Please add my app to the clan!

### ISSUE THREAD

**Issue by codeamt** [blockstack/animal-kingdom#94]
https://jovial-almeida-f5569d.netlify.com/kingdom/codeamt11.id.blockstack

codeamt11.id.blockstack

**Comment by moxiegirl** [comment]
@codeamt Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.


Spacey!
