### ISSUE TITLE
please add my Kingdom to your clan

### ISSUE THREAD

**Issue by kkhcheng** [blockstack/animal-kingdom#95]
https://naughty-bhaskara-17b05c.netlify.com
kkcheng.id.blockstack

**Comment by moxiegirl** [comment]
@kkhcheng Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.


Many, many stars in your kingdom.
