### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by phallv** [blockstack/animal-kingdom#96]
https://musing-joliot-453693.netlify.com

phallvance.id.blockstack

**Comment by moxiegirl** [comment]
@phallv Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.


OK, now you need to go back and add a panther to the animals!
