### ISSUE TITLE
Please add my kingdome to your clan!

### ISSUE THREAD

**Issue by ankit90anand** [blockstack/animal-kingdom#97]
https://quirky-bassi-182eff.netlify.com

ankianan.id.blockstack

**Comment by moxiegirl** [comment]
@ankit90anand  Welcome to the jungle and thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
