### ISSUE TITLE
Please add my kingdom to your clan!

### ISSUE THREAD

**Issue by ani3456** [blockstack/animal-kingdom#98]
https://practical-stallman-b41995.netlify.com

watson_anirudh.id.blockstack

**Comment by moxiegirl** [comment]
@ani3456 Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
